### ISSUE TITLE
Enum State incompatible with value returned by usePlaybackState

### ISSUE THREAD

**Issue by stijnvanderlaan** [doublesymmetry/react-native-track-player#1276] opened 2021-09-22 09:11 UTC
**Describe the bug**
Typescript return type of `usePlaybackState` is a enum `State`, but the to values seem incompatible.
When I log State.Buffering I get a string "loading".
When I log State.Connecting I get undefined.
But when I log the value of the return value of `usePlaybackState` I get "buffering".

**Environment (please complete the following information):**
Run `react-native info` in your project and share the content.
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 3.19 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.0/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /Users/stijn/.rvm/gems/ruby-2.4.3/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7678000
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 9.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: ^0.65.1 => 0.65.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

What `react-native-track-player` version are you using? 2.0.3
Are you testing on a real device or in the simulator? Which OS version are you running?
Real device.

**Code**
Please, share the code that is causing the issue
```
const state = usePlaybackState()
return (
  <Pressable>
    {state === State.Connecting || state === State.Buffering ? (
      <ActivityIndicator color="#c3f8a0" />
    ) : (
      <Icon kind={state === State.Playing ? "small-pause" : "small-play"} />
    )}
  </Pressable>
)
```

**Comment by Nagato717** [comment] 2021-11-12 10:19
+1, btw in my case the state changed from playing -> buffering -> playing again, is it normal?

**Comment by jspizziri** [comment] 2022-04-14 14:02
@stijnvanderlaan @Nagato717 

1. What platform are you seeing this on (Android/iOS/Windows)?
2. Can you see if the issue is still present in v2.2.0-rc3

**Comment by jspizziri** [comment] 2022-04-26 10:55
Closing due to unresponsive issue reporters.

**Closed** 2022-04-26 10:55 UTC
Labels: Bug, Help Wanted, Needs Feedback

**Comment by stijnvanderlaan** [comment] 2022-04-26 11:27
Sorry, yes this seems to be fixed.

**Comment by Kbamborde** [comment] 2024-06-20 10:32
@stijnvanderlaan Can you please suggest  how did you fixed that?
