### ISSUE TITLE
Something seriously wrong with this, doesnt work on any project 

### ISSUE THREAD

**Issue by huncrew** [DoubleSymmetry/react-native-track-player#1265] opened 2021-09-16 20:08 UTC
on an M1 macbook..

same errors, different projects 

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.google.android.exoplayer:exoplayer-core:2.11.4.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
       - file:/Users/dalegrant/.m2/repository/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
       - file:/Users/dalegrant/Documents/JukeBox/node_modules/react-native/android/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
       - file:/Users/dalegrant/Documents/JukeBox/node_modules/jsc-android/dist/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
       - https://dl.google.com/dl/android/maven2/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
       - https://www.jitpack.io/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
     Required by:
         project :app > project :react-native-track-player

**Comment by dcvz** [comment] 2021-09-16 21:33
Duplicate of https://github.com/DoubleSymmetry/react-native-track-player/issues/1235

**Closed by dcvz** 2021-09-16 21:33 UTC
Labels: Bug, Needs Confirmation
