### ISSUE TITLE
Android - TrackPlayer.add() is not stable

### ISSUE THREAD

**Issue by iboxgithub** [doublesymmetry/react-native-track-player#1797] opened 2022-10-12 15:52 UTC
**Describe the Bug**
To reproduce, just select and play a song
When doing a TrackPlayer setup, we have this code below which works consistently on iOS but fails ~60% of the time on Android:

> await TrackPlayer.reset();
> console.log('tracksTemp.length: ', tracksTemp.length);  `// tracksTemp.length: 3`
> console.log('selectedTrackIndex: ', selectedTrackIndex); `// selectedTrackIndex: 2`
> await TrackPlayer.add(tracksTemp);
> console.log('TrackPlayer.getQueue: ', (await TrackPlayer.getQueue()).length); `// TrackPlayer.getQueue: 2`
> await TrackPlayer.skip(selectedTrackIndex);`

**Error:**
<img width="757" alt="image" src="https://user-images.githubusercontent.com/5391993/195389426-4f89ebaa-1c75-41d6-abe4-94d00b695696.png">

**Environment Info:**
Paste the results of `npx react-native info`

`info Fetching system and libraries information...
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Max
    Memory: 117.20 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.10.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
    Watchman: 2022.10.03.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.6 => 0.69.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.70.3 is now available (your project is running on v0.69.6).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.70.3.
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.69.6.
info To upgrade, run "react-native upgrade".`

Paste the exact `react-native-track-player` version you are using
"react-native-track-player": "2.2.0-rc3",

Real device? Or simulator?
Simulator

What OS are you running?
Android 33

**Comment by jspizziri** [comment] 2022-10-13 15:51
@iboxgithub 

First, you're using a super old version of RNTP (`v2.2.0-rc3`), please upgrade to the latest version.

If you're still getting this issue on the latest version then these are my thoughts:

it looks like the issue is that one of your tracks is failing to `add` and then you're attempting to access an index that doesn't exist (which makes sense that it's throwing an exception, although it should probably not crash your app, but bubble up through the error event api).

**Comment by jspizziri** [comment] 2022-10-17 17:01
@iboxgithub if I don't hear anything back soon, I'm going to close this issue.

**Comment by iboxgithub** [comment] 2022-10-17 17:42
Apologies, so we manage to upgrade to 3.1.0 which solves the issue. Otherwise too many missing dependencies with expo 46. Thanks for your help!

**Closed** 2022-10-17 17:54 UTC
Labels: Bug, Platform: Android, Needs Feedback, Unconfirmed
