### ISSUE TITLE
App won't run

### ISSUE THREAD

**Issue by huncrew** [DoubleSymmetry/react-native-track-player#1261] opened 2021-09-16 11:41 UTC
Followed install instructions,

Error: 
> Task :app:checkDebugAarMetadata FAILED
6 actionable tasks: 2 executed, 4 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.google.android.exoplayer:exoplayer-core:2.11.4.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
       - file:/Users/dalegrant/.m2/repository/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
       - file:/Users/dalegrant/Documents/JukeBox/node_modules/react-native/android/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
       - file:/Users/dalegrant/Documents/JukeBox/node_modules/jsc-android/dist/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
       - https://dl.google.com/dl/android/maven2/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
       - https://www.jitpack.io/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
     Required by:
         project :app > project :react-native-track-player

Notes: 

I am running npx react-native run-android

**Comment by dcvz** [comment] 2021-09-16 21:37
Duplicate of #1235

**Closed** 2021-09-16 21:38 UTC
Labels: Bug, Needs Confirmation
