### ISSUE TITLE
[Android] App is getting crash when we restart the application

### ISSUE THREAD

**Issue by cihanbas** [doublesymmetry/react-native-track-player#1851] opened 2022-12-15 08:08 UTC
Hi Thanks for this great library...

**Describe the Bug**
When we restart app with `react-native-restart` and then when we call isSetup function the app getting crash

**Steps To Reproduce**
run the application and play any audio then restart app and play audio again,

**Code To Reproduce**
setupService.tsx
```javascript
import TrackPlayer, {
    AppKilledPlaybackBehavior,
    Capability,
} from 'react-native-track-player';

export const SetupService = async (): Promise<boolean> => {
    let isSetup = false;
    try {
        // this method will only reject if player has not been setup yet
        await TrackPlayer.getCurrentTrack();
        isSetup = true;
    } catch {
        await TrackPlayer.setupPlayer();
        await TrackPlayer.updateOptions({
            android: {
                appKilledPlaybackBehavior:
                    AppKilledPlaybackBehavior.StopPlaybackAndRemoveNotification,
            },
            // This flag is now deprecated. Please use the above to define playback mode.
            // stoppingAppPausesPlayback: true,
            capabilities: [
                Capability.Play,
                Capability.Pause,
                Capability.SkipToNext,
                Capability.SkipToPrevious,
                Capability.SeekTo,
            ],
            compactCapabilities: [
                Capability.Play,
                Capability.Pause,
                Capability.SkipToNext,
            ],
            progressUpdateEventInterval: 2,
        });

        isSetup = true;
    } finally {
        // eslint-disable-next-line no-unsafe-finally
        return isSetup;
    }
};

```
Home.tsx
```javascript 
import { StyleSheet, Text, View, Button } from 'react-native'
import React from 'react'
import RNRestart from 'react-native-restart'; // Import package from node modules

const Home = ({ navigation }) => {
    return (
        <View style={styles.container}>
            <Button title='Video' onPress={() => navigation.navigate('Video')}></Button>
            <Button title='Audio' onPress={() => navigation.navigate('Audio')}></Button>
            <Button title='Restart' onPress={() => RNRestart.Restart()}></Button>
        </View>
    )
}

export default Home

const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'space-around'
    }
})
```
index.js
```javascript 
/**
 * @format
 */
import TrackPlayer from "react-native-track-player"

import { AppRegistry } from 'react-native';
import App from './App';
import { name as appName } from './app.json';
import { PlaybackService } from "./service";
AppRegistry.registerComponent(appName, () => App);
TrackPlayer.registerPlaybackService(() => PlaybackService);
```

**Replicable on Example App?**
Can you replicate this bug in the [React Native Track Player Example App](https://github.com/doublesymmetry/react-native-track-player/tree/main/example)?

**Environment Info:**
```
System:
    OS: macOS 12.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 496.35 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.6.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.13.2 - /usr/local/bin/npm
    Watchman: 2022.07.04.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4/13F17a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.2 => 0.70.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**How I can Help**
I guess the problem is about the this block 
```javascript 
TrackPlayer.registerPlaybackService(() => PlaybackService);
```

**Comment by tdammy92** [comment] 2022-12-23 22:44
Any fix with this  ?? ,  getting d same issue, happy crashes on first launch, but okay on subsequent launch

**Comment by MustagheesButt** [comment] 2023-01-02 07:32
This is an issue with KotlinAudio. It has been fixed by the team but not released yet. See https://github.com/doublesymmetry/react-native-track-player/issues/296 for how to fix it for your project

**Comment by cihanbas** [comment] 2023-01-03 08:47
> 
@tdammy92 it is working for me you can check it
https://github.com/doublesymmetry/react-native-track-player/issues/296#issuecomment-1312526414

**Comment by jspizziri** [comment] 2023-02-27 13:42
As several people have mentioned, this looks like a duplicate of an already resolved issue. Please upgrade to the latest RC and see if it's still happening. If it is please document the specific error message that you're getting and we can reopen this issue.

**Closed by jspizziri** 2023-02-27 13:42 UTC
Labels: Bug
