### ISSUE TITLE
Not able to run remote urls on Android 9

### ISSUE THREAD

**Issue by ashrafghanem** [DoubleSymmetry/react-native-track-player#730] opened 2019-09-09 19:07 UTC
# Configuration

I am using react-native-track-player version 1.1.8

# Issue

I am using the module to play remote url. 
It works fine for all android versions less than 9 (Pie)
on Android 9, it fails to play from remote url while it can play a local audio file!

The url is a live streaming server, here it is: http://www.quran-radio.org:8002/i

Is there a solution for this issue?

**Comment by denkata** [comment] 2019-09-15 10:34
On Android 9 and above unencrypted traffic is disallowed by default. Since your stream URL is not using https it will not play. 

To turn off this setting, add this to your `AndroidManifest.xml`:

`android:usesCleartextTraffic="true" `

**Comment by Guichaguri** [comment] 2019-10-21 01:59
This should probably be added to the documentation at some point. I'll mark it as "docs" so we don't forget to do so.

**Comment by kranthikumar-uppula** [comment] 2019-11-05 19:46
I too facing same issue. added android:usesCleartextTraffic="true" in android/app/src/debug/AndroidManifest.xml, but still the issue is not fixed in Android 9 and above.
in Android 8 and below no issue.

**Comment by Guichaguri** [comment] 2019-11-21 15:16
Are you seeing any error or warning logs?

**Closed** 2021-08-10 16:52 UTC
Labels: Docs
