### ISSUE TITLE
App is closing immediately when i call TrackPlayer.setupPlayer() in android 

### ISSUE THREAD

**Issue by Krish143git** [doublesymmetry/react-native-track-player#1485] opened 2022-04-21 19:09 UTC
hi this issue still reproducing regards #1474  
 still i am facing the same issue.@JDMathew as per your comments i tried still issue is not resolved. 

@JDMathew. 
1) i tried with 2.2.0-rc2 and rc3  getting below error (The below line is repeating plenty of times)
Duplicate class (rc2)com.google.android.exoplayer2.upstream.cache.CacheDataSink found in modules exoplayer-core-2.13.2-runtime.jar (com.google.android.exoplayer:exoplayer-core:2.13.2) and exoplayer-datasource-r2.16.4-runtime.jar (com.github.DoubleSymmetry.ExoPlayer:exoplayer-datasource:r2.16.4)

2)2.2.0- rc1   getting below error : Duplicate class com.google.android.exoplayer2.video.spherical.CameraMotionRenderer found in modules exoplayer-core-2.13.2-runtime.jar (com.google.android.exoplayer:exoplayer-core:2.13.2) and exoplayer-core-r2.16.4-runtime.jar (com.github.DoubleSymmetry.ExoPlayer:exoplayer-core:r2.16.4) 

3) tried with lastest 2.1.3 errors attaching the screen shot :
<img width="268" alt="Screenshot 2022-04-22 at 12 34 20 AM" src="https://user-images.githubusercontent.com/80909154/164534937-78494f72-b23b-4d92-8472-be0d0510c42e.png">

**Comment by jspizziri** [comment] 2022-04-21 20:17
@Krish143git this looks like a duplicate of https://github.com/doublesymmetry/react-native-track-player/issues/1418

I'm going to close it but if you think it's a unique issue please let me know.

**Closed by jspizziri** 2022-04-21 20:17 UTC
Labels: Bug

**Comment by Krish143git** [comment] 2022-04-22 03:30
@jspizziri  Here i tried with Rc packages because of the @JDMathew comment on ticket #1485 the above errors i am getting . Real my ticket is duplate of #1418  but i am reopening this ticket from #1485

**Comment by jspizziri** [comment] 2022-04-22 09:55
@Krish143git , we're not going to fix android issues on 2.1.3 or any version lower than 2.2.0 because of the rewrite. So the only addressable issues here are the duplicate exoplayer problem which is already in our radar.

**Comment by cristiankmb** [comment] 2022-05-03 18:27
@Krish143git Did you manage to run your app or are you still getting the duplicate libraries error or the shutdown error when setting `TrackPlayer.setupPlayer();` ? I have 2 days trying to setup react-native-track-player in my project again but i couldn't.

```
"react": "17.0.2",
"react-native": "0.68.1",
```
Version that i tried:

```
"react-native-track-player": "^2.1.3", // Close App
"react-native-track-player": "^2.2.0-rc2", // Plugin with id 'kotlin-android' not found.
"react-native-track-player": "^2.2.0-rc3", // Duplicate package names
```

Sorry for re-open

**Comment by jspizziri** [comment] 2022-05-03 18:47
The kotlin plug-in issue was fixed in rc3 (as you're seeing). The duplicate package issue is a known issue with exoplayer that hasn't been fixed yet.

**Comment by Krish143git** [comment] 2022-05-05 06:42
@cristiankmb  Hi, I am using react-native-video with react-native-track-player my issue is with exo player.Bro If you are not using react-native-video please try to use 1.2.7 version of track player it is working for me .I tried later versions also still i did not got any solution.Bro if 1.2.7 is not worked then from 2.1.3 try every version by downgrading may be this will help you. please refer  #1450 you will get some new info that i faced

**Comment by cristiankmb** [comment] 2022-05-05 23:31
@Krish143git  Thanks bro, that's why I ask you, Right now I can't make react-native-track-player work in my project 😩. I'm using the same libraries, react-native-video react-native-track-player. I'm using these libraries since V1.0.2, even i have another project with react-native minor version and react-native-track-player@2.1.3.  But I updated my project to most lasted react-native version and now I can't make react-native-track-player work, I suppose that i need wait for a stable -rc or stable version. 

PD: I had already read all your posts before posting my question. 😅
