### ISSUE TITLE
Could not find com.google.android.exoplayer:exoplayer-core:2.11.4.

### ISSUE THREAD

**Issue by GoodNews-Myanmar-Developer** [DoubleSymmetry/react-native-track-player#1283] opened 2021-09-26 07:45 UTC
I got this error, I don't know how to fix. Please help me

 What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.google.android.exoplayer:exoplayer-core:2.11.4.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
       - file:/C:/Users/user/.m2/repository/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
       - file:/C:/Users/user/Projects/react-native/bare/real/goodnewsmyanmar/node_modules/react-native/android/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
       - file:/C:/Users/user/Projects/react-native/bare/real/goodnewsmyanmar/node_modules/jsc-android/dist/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
       - https://dl.google.com/dl/android/maven2/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom       
       - https://www.jitpack.io/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
     Required by:
         project :app > project :react-native-track-player

**Comment by Tucker2015** [comment] 2021-09-26 14:22
Please see https://github.com/DoubleSymmetry/react-native-track-player/issues/1235#issue-975130415

**Comment by dcvz** [comment] 2021-09-27 12:02
As mentioned this is a duplicate of #1235 closing this.

**Closed by dcvz** 2021-09-27 12:02 UTC
Labels: Bug, Needs Confirmation
