### ISSUE TITLE
Configurable Progress Updated Events

### ISSUE THREAD

**Issue by martinmidtsund** [doublesymmetry/react-native-track-player#1414] opened 2022-02-24 08:32 UTC
**What is the need and use case of this feature?**
There are two use-cases for this feature request, that I have run into:

1. For a podcast application, sleep functionality, that is to set a timer and pause the playback after the given time, is commonly supported in podcast applications. For now with RNTP we have to either implement a native module ourselves for Android, or use the not so well maintained library of react-native-background-timer to set a timeout that runs in the background. For iOS the app seems to be kept alive to run a regular JS-timeout when it is playing music. With a progress event this could be a simple timestamp check, that even works in the background without any problems or extra libraries.

2. In stead of setting an interval with aforementioned react-native-background-timer, or an own implementation in Android, the progress events could be used for analytics (e.g. send analytics event to backend, store listening position to resume if paused etc.).

**Describe the ideal solution**
Triggers an event with the current position on a given timeinterval (e.g. not too often to avoid overhead, but perhaps every 2/5/10 seconds), we could query the track player for the rest of the information we need. This needs to happen natively, so we can listen to the event in the background-service and handle the events when the app is in the background.

**Describe alternatives you've considered**
Aforementioned library react-native-background-timer makes this currently possible on Android, and setTimeout/setInterval works out of the box on iOS when audio is playing.

**Additional context**
It seems like SwiftAudioEx already has this configuration with the option `timeEventFrequency`.
I haven't found the same on ExoPlayer. There is an issue on this here: https://github.com/google/ExoPlayer/issues/6504

**How I can Help**
What can you do to help get this feature into production?
I can test the implementation, and join the discussion on a high level.
Can you assist by working on this feature and creating a Pull Request?
No, not currently.

**Comment by jspizziri** [comment] 2022-04-12 17:46
@dcvz this is something that I'm interested in too. @martinmidtsund 's points about supporting sleep timers and background progress updates during headless playback on Android are the exact same problems I'm looking to solve as well.

I'd be happy to work on the implementation here if we had some architectural consensus (specifically if there's a better way to do this from your perspective). From my perspective, I think that a periodic event that would fire every `X` interval _IF_ the underlying player was still playing would be great.

**Comment by dcvz** [comment] 2022-04-12 19:49
@martinmidtsund @jspizziri -- so the use case is a bit of a replacement for the current progress hook? which currently fires every second or so.. you instead want to be able to configure the time interval? Plus, you want it to not go via react but through the events system?

I guess the problem is that for your cases you only want longer intervals if the app is in the background right? How would you control that? Also even if you could configure the interval at which progress is fired, how would that help you make a timer so you know when to stop playback if the user set a timer? By saving a timestamp?

**Comment by jspizziri** [comment] 2022-04-12 20:43
@dcvz at the core the issue largely revolves around headless playback (on Android specifically).

Here are my answers to your questions followed by a more specific outline of the problems I'm trying to solve:

# Answers To Your Questions

> so the use case is a bit of a replacement for the current progress hook? which currently fires every second or so.. you instead want to be able to configure the time interval? Plus, you want it to not go via the hook but through the event system?

Yes and no. We use `useProgress` to update the position of our playback progress bar, however, for updating stored progress we use `setInterval` that runs in our "Service" periodically (because of headless). It's only a replacement for the progress hook in the sense that the progress hook doesn't work in headless contexts, and for that same reason an Event is what comes to mind for me. 

> I guess the problem is that for your cases you only want longer intervals if the app is in the background right? How would you control that? 

Most specifically, the problem is that there is no way of getting progress during playback in headless contexts on Android. Things like `setInterval` to poll progress periodically don't work. An event system would allow for the execution of some JS code periodically during headless playback (e.g. update saved progress & check sleep timer). With that said, if such an event existed, the `useProgress` hook could be refactored to take advantage of it rather then using `setInterval` itself.

> Also even if you could configure the interval at which progress is fired, how would that help you make a timer so you know when to stop playback if the user set a timer? By saving a timestamp?

To be clear, I don't see configurable intervals as a must-have, I could probably get away with debouncing events or something like that. However, the way we're doing sleep timers on iOS is by saving a timestamp, and then checking the current time against it in a `setInterval` loop (which again, works on iOS but not on Android). When the time is reached we stop playback. However, this problem could be solved in another way by passing a timestamp or interval to the native side and having the native side stop playback internally. That would work for me too; however, an event could allow both problems to be solved by a single solution (not that that makes it a good solution).

# More Problem Detail

#### Progress Tracking

1. If you're storing user playback progress in a database somewhere then you need to update that progress when a user is playing back headlessly.
2. The `useProgress` hook only works when the app's UI is rendered, and doesn't fire when playing in headless mode.

#### Sleep Timers

This is a variation of the same Progress issue. If a user sets a sleep timer and then is playing back in a headless context you need to be able to check periodically if their timer has expired to stop playback.

**Comment by dcvz** [comment] 2022-04-12 21:11
Ok, seems like I understand you particular issue @jspizziri -- although maybe not quite what the title suggests.

It seems that we could have progress, be driven by an event (and the hook can also observe that, just like it does for state).. this would also make it so on Android it fires the headless task.. **however**, progress updates happen very regularly so you'll be getting an event every second. I'm not sure how good of an idea that is.

I also still don't know how you'd use it for a timer functionality. `debounce` and other timer based functions will not work in headless.

--- 

I think if we did want an event based "progress update" it'd have to be configurable to some time interval, so the developer can decide how aggressive they want to be.. and it shouldn't fire unless the developer has configured an interval. We would likely not use it to drive the progress hook.

**Comment by jspizziri** [comment] 2022-04-12 21:54
@dcvz I agree that the title isn't exactly what I'm expressing, but my understanding of the use-cases described by @martinmidtsund does line up (sorry if I'm accidentally hijacking this issue, but I think we're on the same page).

Your comments all make sense to me regarding making it configurable and not fire unless configured.

As an aside, here's how you would use an event to implement a sleep timer:

1. The user configures a sleep timer in the UI.
2. You persist the time they configure in a store.
3. Each time the progress event fires you check your persisted sleep timer timestamp. If it exists and it's been hit then you pause.

I don't think it's ideal, but it's the only solution I can think of short of allowing a sleep time to be passed directly to the native side (which I'm open to). If you're interested in supporting sleep timers first-class then perhaps we should have a separate conversation around that. Conceptually though, you could just have an interface like`TrackPlayer.setSleepTimer(time: Date | null)` and then of course the native side would need to do some magic.

**Comment by martinmidtsund** [comment] 2022-04-12 22:47
Hi!

It seems like we are pretty much aligned, yes.

@jspizziri No worries, glad to have a discussion on it. Even though I'll be away on holidays until next week so I probably will be silent until then. :)

@dcvz Thanks for replying, and I'll try to answer your questions from my point of view.

> so the use case is a bit of a replacement for the current progress hook?

Not a replacement, I think these could live side by side?

> which currently fires every second or so.. you instead want to be able to configure the time interval?

A configurable interval is not an absolute need for us, as long as it is often enough to collect good analytics (no more than 5-10 seconds) and have a pretty recent continue listening position. I do however agree with your reasoning that it should be configurable, and not even fire at all if not configured, this way it will fit more use-cases.

> Plus, you want it to not go via the hook but through the event system?

Yes, to be able to collect the events in the background in your backgroundservice.

> I guess the problem is that for your cases you only want longer intervals if the app is in the background right?

No, we want to use the longer interval and events even in the foreground, as the analytics and continue listening part is just as important in both states. In the foreground the useProgress hook will also fire at a much higher rate, we are currently at 250 ms, and we use it for the UI. I know we could have used the useProgress hook in the foreground, but it seems better to have one solution that works in both states.

> How would you control that? Also even if you could configure the interval at which progress is fired, how would that help you make a timer so you know when to stop playback if the user set a timer? By saving a timestamp?

Yes, by checking against a timestamp. But I think the solution proposed by @jspizziri to have first-class sleep-timer functionality would be better.

The only reason I mentioned these use-cases together, was that I could see a progress-event could help with all of them (analytics, continue listening and sleep timer) in both foreground and background. The sleep timer, as mentioned, would probably be much better if it could be set on its own and triggered on the native side on track-end (or even after multiple tracks if someone wanted to 😱) or on a timeout.

We have this working today on both iOS (supported out of the box with setInterval/setTimeout) and Android (react-native-background-timer which is using a Handler to run setInterval/setTimeout in background), where we get analytics, store continue listening positions and occasionally send these back to the server on a 5 second interval. But I am not sure how long the background-timer package will work, as it is not actively maintained it seems. And for the sleep-timer, we're setting a timeout or check on PlaybackTrackChanged if the sleep-mode is set to track-end.

Thank you for your time, hope I made some sense, it's getting late. :)

**Comment by jspizziri** [comment] 2022-04-12 23:05
Thanks for the feedback @martinmidtsund , I feel like we're definitely aligned.

**Comment by jspizziri** [comment] 2022-04-13 19:09
@dcvz , sounds great to me. I'll take a crack at the implementation in the next week or so.

**Comment by johkade** [comment] 2022-04-15 16:58
I second all of what was said before. This would be a great addition to this library. I'm currently doing practically the same as martinmitsundt using r-n-background-timer

**Comment by jspizziri** [comment] 2022-04-19 16:56
I've got [a largely functional PR](https://github.com/doublesymmetry/react-native-track-player/pull/1473) up (for Android & iOS) if anyone cares to take a look.

**Comment by jspizziri** [comment] 2022-04-29 14:15
This MR was just merged into `main` and will be available with the next RC! 🎊 

Please feel free to take it for a spin in the example project.

**Closed by jspizziri** 2022-04-29 14:15 UTC
Labels: Feature Request
