### ISSUE TITLE
RepeatMode.Queue doesn't repeat the queue if there is only one track in queue

### ISSUE THREAD

**Issue by kyimoemin** [doublesymmetry/react-native-track-player#1583] opened 2022-06-25 17:16 UTC
**Describe the Bug**
`RepeatMode.Queue` doesn't repeat the queue if there is only one track in the queue and the progress is stopped at the end of the duration and didn't reset to 0.

**Steps To Reproduce**
Play the queue with only one track with the `RepeatMode.Queue`

**Code To Reproduce**
```js
...
TrackPlayer.add(track);
TrackPlayer.setRepeatMode(RepeatMode.Queue);
TrackPlayer.play(); 

```

**Environment Info:**
System:
    OS: macOS 12.4
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 34.04 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.13 - /usr/local/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 27, 28, 29, 30, 31
      Build Tools: 29.0.2, 30.0.3, 31.0.0
      System Images: android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
`react-native-track-player`:`^2.1.2`
Simulator
MacOs

**Comment by jspizziri** [comment] 2022-06-25 19:44
@kyimoemin Thanks for the report. This is a known and already reported issue which has been worked on in this PR. Please read there for all the details.

https://github.com/doublesymmetry/react-native-track-player/pull/1501

**Comment by jspizziri** [comment] 2022-06-25 19:45
I'll also add that I closed it as a duplicate of the issues already linked to the ticket.

**Closed** 2022-06-25 19:44 UTC
Labels: Bug
