### ISSUE TITLE
App killed when notification stop button is pressed

### ISSUE THREAD

**Issue by ThomasArrt** [doublesymmetry/react-native-track-player#1768] opened 2022-09-30 14:45 UTC
**Describe the Bug**
While trying to upgrade the package, we've used the nightly version with the fix killing the tracker when the app is killed (on Android). With this version, pressing compact notification stop button kill the app.

**Steps To Reproduce / Replicable on Example App?**
Install example app. Add stop button on notification. Launch a music and press this button.

**Code To Reproduce**
` src/services/SetupService.ts     
 compactCapabilities: [
        Capability.Play,
         Capability.Pause,
        Capability.Stop,
      ],`

Can you replicate this bug in the [React Native Track Player Example App](https://github.com/doublesymmetry/react-native-track-player/tree/main/example)?

**Environment Info:**
`System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 114.28 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.1/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
    Watchman: 2022.09.19.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.0/14A309 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.1 => 0.68.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found`

Paste the exact `react-native-track-player` version you are using
"react-native-track-player": "^3.2.0-e742959cc1d697d69daeade39830155bce2ccde7",

Real device? Or simulator? Real Device

What OS are you running? iOS - Mac

**Comment by hafizMDM** [comment] 2022-10-02 17:21
Yes. This issue was introduced once this line is added. 

https://github.com/doublesymmetry/react-native-track-player/commit/e742959cc1d697d69daeade39830155bce2ccde7#diff-5f8591a257348c4875d613bf1dad66a989949b38117fa649c9db24a30cbe0708R404


This also affect when reset is called.

**Comment by hafizMDM** [comment] 2022-10-13 08:20
@abdouAoufi 

I switched from the nightly build to 3.2.0 and handled the notification dismiss separately from my app when app is removed from the background.

**Comment by abdouAoufi** [comment] 2022-10-13 10:30
I did the same thank you!

**Comment by Ryabchikus** [comment] 2022-11-02 10:20
Hello
I have so close problem
I use RNTP@3.1 because of v3.2 requires sdk33
When I press 'stop' button on android notification, then sound stops, notification gone, it is correct, but i can't start playing again until my app restarts
in system log i see
```
11-02 12:50:33.610 30488 30571 V AudioManager: playSoundEffect   effectType: 0
11-02 12:50:33.613 30488 30570 I ReactNativeJS: getCurrentTrack works // here call getCurrentTrack() for check player's state like in example, here is no excepton
11-02 12:50:33.633 30488 30570 I ReactNativeJS: 'getState', { state: 0 } // another try, getState(); state present, player was setup
11-02 12:50:33.661 30488 30570 I ReactNativeJS: 'handleTogglePlayback', // try to start playing
11-02 12:50:33.691  1337  2302 I avrcp-Avrcp: Skipping update due to invalid playback state
```
In version 1 I checked player's state and did somethink like 
```
await TrackPlayer.destroy()
await TrackPlayer.setupPlayer()
await TrackPlayer.add(...)
```
and call play()
Can you advise me any workaround? 

ps. Sorry my english :-)

**Comment by SyedTayyabUlMazhar** [comment] 2022-11-03 17:35
> @abdouAoufi
> 
> I switched from the nightly build to 3.2.0 and handled the notification dismiss separately from my app when app is removed from the background.

How did you do that?

**Comment by dimadeveatii** [comment] 2022-11-23 10:44
> @abdouAoufi
> 
> I switched from the nightly build to 3.2.0 and handled the notification dismiss separately from my app when app is removed from the background.

I can confirm the same issue is reproducible for our app.  
@abdouAoufi could you help with a code snippet on how you managed to dismiss the notification separately?

**Comment by hafizMDM** [comment] 2022-12-08 10:14
@elliotdickison 
In my case that I used reverted to stable version (3.2.0) and use https://www.npmjs.com/package/react-native-exit-app to kill the app when the app is dismissed from the background. 

Your entry component (index.tsx) will unmount when the app is removed from the background. You can use the above library on cleanup.

**Comment by puckey** [comment] 2023-02-18 13:12
This is fixed in nightly.

**Closed by puckey** 2023-02-18 13:12 UTC
Labels: Bug, Platform: Android
