### ISSUE TITLE
`RemoteSeek` event not triggering on Android 13 notification.

### ISSUE THREAD

**Issue by Dajust** [doublesymmetry/react-native-track-player#1877] opened 2023-01-16 19:33 UTC
**Describe the Bug**
On Android 13, the notification seek slider is always active even when it is not included in the Media Controls Capabilities array. 
Also, when you use the slider on the notification to seek to a new position, the `RemoteSeek` event is never fired.

**Steps To Reproduce**
I tested on Android 13, not sure about older android versions. 
Make sure that `Capability.SeekTo` is not included in the `capabilities` array.

 ```js 
 capabilities: [
      Capability.Play,
      Capability.Pause,
      Capability.SkipToNext,
      Capability.SkipToPrevious,
     // we DON'T want to seek from remote
     //  Capability.SeekTo,
    ]
   ```
Rebuild and observe that the seek slider is always active and functioning.

Now add the `seekTo` capability.
 ```js 
 capabilities: [
      Capability.Play,
      Capability.Pause,
      Capability.SkipToNext,
      Capability.SkipToPrevious,
     // we want to seek from remote
     Capability.SeekTo,
    ]
   ```
    
Rebuild, then Observe that the `Event.RemoteSeek is never fired` although the seek is actually functioning.

**Code To Reproduce**
NA

**Replicable on Example App?**
Yes

**Environment Info:**
```bash
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Memory: 163.78 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.1/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7486908
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: ^0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.71.0 is now available (your project is running on v0.70.6).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.71.0
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.70.6
info For more info, check out "https://reactnative.dev/docs/upgrading".
```

**How I can Help**
What can you do to help resolve this?
Have you investigated the underlying JS or Swift/Android code causing this bug?
Can you create a Pull Request with a fix?

**Comment by puckey** [comment] 2023-02-18 13:19
Interesting – have you tested this using the `nightly` version?

**Comment by samihabuawadSL** [comment] 2023-02-19 17:06
I did test with nightly version installed today, still not working

**Comment by puckey** [comment] 2023-02-20 10:46
I was able to fix  the issue where the `Event.RemoteSeek` event was not being emitted through the following pr https://github.com/doublesymmetry/KotlinAudio/pull/63

**Comment by puckey** [comment] 2023-02-20 10:59
I believe the rest of your issue is a duplicate of https://github.com/doublesymmetry/react-native-track-player/issues/1775

**Closed** 2023-02-22 15:19 UTC
Labels: Bug
