### ISSUE TITLE
Upgrading from 1.2.7 to 2.0.2

### ISSUE THREAD

**Issue by ebrahimmelngary** [DoubleSymmetry/react-native-track-player#1233] opened 2021-08-18 00:43 UTC
**Describe the bug**

app build success but not open

 ERROR  TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[9], "react-native-track-player").TrackPlayerEvents.PLAYBACK_ERROR')
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling run application). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

**To Reproduce**

**Environment (please complete the following information):**
"react-native-track-player":"2.0.2"
"react-native": "0.64.2",
![Screen Shot 2021-08-18 at 2 34 42 AM](https://user-images.githubusercontent.com/26544537/129818427-71a21472-cc31-4e3e-9bd1-7319f532f3a4.png)

**Code**
  TrackPlayerEvents,
not found

**Comment by hiroyaiizuka** [comment] 2021-08-18 01:27
@ebrahimmelngary 

TrackPlayerEvents API is different from older version.

 are these codes for your help?
 
 ```
 
 import TrackPlayer, {
-  STATE_READY,
-  STATE_PLAYING,
+  State,
+  Capability,
+  Event,
 } from 'react-native-track-player'

```

```

     const onPlayerStateChange = TrackPlayer.addEventListener(
-      'playback-state',
-      async props => {
-        if (iOS && props.state === STATE_READY) {
+      Event.PlaybackState,
+      async (props) => {
+        const state = await TrackPlayer.getState()
+        if (iOS && state === State.Ready) {


```

**Comment by dcvz** [comment] 2021-08-19 07:38
Thank you for giving an answer here @hiroyaiizuka !
@ebrahimmelngary I've better documented some of the breaking changes going into v2 in the README

**Comment by dcvz** [comment] 2021-08-19 07:40
I will close this now as its not a bug, I hope the README provides all the information needed now.

**Closed by dcvz** 2021-08-19 07:40 UTC
Labels: Bug, Needs Confirmation
