### ISSUE TITLE
Audio stops when camera opened on IOS

### ISSUE THREAD

**Issue by annakoro** [doublesymmetry/react-native-track-player#1429] opened 2022-03-07 13:13 UTC
**Describe the Bug**
Audio stops when camera opened on IOS. I expect it to continue playing when I close the camera.

**Steps To Reproduce**
How can someone else reproduce this bug?
1. Play any audio 
2. Get out of the application (audio still playing)
3. Open phone camera
4. Record a video (audio stops playing)
5. Observe

**Code To Reproduce**
Please provide a simple code example that allows others to replicate the bug.

**Environment Info:**
Paste the results of `npx react-native info`
System:
    OS: macOS 11.6
    CPU: (8) x64 Apple M1
    Memory: 60.34 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.22.13 - ~/.nvm/versions/node/v14.15.0/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
    Watchman: 2022.01.03.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.1 => 0.65.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Paste the exact `react-native-track-player` version you are using
2.1.2

Real device? Or simulator?
real device
What OS are you running?
14.8.1

**How I can Help**
What can you do to help resolve this?
Have you investigated the underlying JS or Swift/Android code causing this bug?
Can you create a Pull Request with a fix?

**Comment by jspizziri** [comment] 2022-04-19 18:14
I've confirmed this behavior, however after looking more deeply into it looks like:

1. This issue should actually be filed with [SwiftAudioEx](https://github.com/doublesymmetry/SwiftAudioEx)
2. This is really a feature request and not a bug.

With both of those things in mind, I'm going to close this issue. If you disagree please let me know.

**Closed by jspizziri** 2022-04-19 18:14 UTC
Labels: Bug, Platform: iOS
