### ISSUE TITLE
PlaybackTrackChanged event fires multiple time and returns inaccurate data

### ISSUE THREAD

**Issue by andrewdang17** [doublesymmetry/react-native-track-player#1462] opened 2022-04-05 15:07 UTC
**Describe the Bug**
The `PlaybackTrackChanged` fires twice on the first song I play, then 3 times on any other song that is not at index 0. Here's what it looks like:

* Playing first song in queue
Here I expect `nextTrack` to equal 1. `position` is always 0
```
 LOG  {"position": 0, "track": 0, "type": "playback-track-changed"}
 LOG  {"nextTrack": 0, "position": 0, "type": "playback-track-changed"}
```
* Selecting next song manually 
Here I expect `nextTrack` to equal 2. `position` is still always 0. The first event always returns but with no `nextTrack` property
```
 LOG  {"position": 0, "track": 0, "type": "playback-track-changed"}
 LOG  {"nextTrack": 0, "position": 0, "type": "playback-track-changed"}
 LOG  {"nextTrack": 1, "position": 0, "track": 0, "type": "playback-track-changed"}
```

**Steps/code To Reproduce**
I have a list of song rows and when clicking any row, the player is reset, tracks are re-added from the current screen, player skips to the next track, and then play. This is all done inside a generator function from mobx-state-tree (see [async actions](https://mobx-state-tree.js.org/concepts/async-actions)), hence the `yield` instead of `await`, which is similar to redux-saga.
```
const tracks = songData.reduce(s => ({
  acc.push({
    id: s.id,
    url: s.mp3,
    title: s.title,
    artist: s.artist,
    duration: s.duration,
}, acc)

yield TrackPlayer.reset()
yield TrackPlayer.add(tracks)
const trackIndex = self.songIds.indexOf(song.id)
yield TrackPlayer.skip(trackIndex)
yield TrackPlayer.play()
```

**Environment Info:**
```
System:
    OS: macOS 12.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 35.80 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.asdf/installs/nodejs/16.14.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.3.1 - ~/.asdf/plugins/nodejs/shims/npm
    Watchman: 2022.02.14.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 29, 30
      Build Tools: 30.0.2, 32.0.0
      System Images: android-Tiramisu | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.67.2 => 0.67.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
Version 2.1.3
Simulator, IOS 13.7 on iPhone 11

**How I can Help**
What can you do to help resolve this?
Have you investigated the underlying JS or Swift/Android code causing this bug?
Can you create a Pull Request with a fix?

**Comment by jspizziri** [comment] 2022-04-17 14:21
@andrewdang17 Do you have the ability or interest to do some deeper investigation here? Happy to provide some guidance!

**Comment by andrewdang17** [comment] 2022-04-17 21:13
@jspizziri yes that would be great!

**Comment by jspizziri** [comment] 2022-04-19 17:01
@andrewdang17 awesome, let me know what questions you have. Looking forward to your PR!

**Comment by jspizziri** [comment] 2022-04-19 21:28
@andrewdang17 after doing a little bit of digging here it looks like this is only an issue with `RepeatMode.Track`, can you confirm?

**Comment by jspizziri** [comment] 2022-04-19 21:42
@andrewdang17 just submitted a fix for this issue: https://github.com/doublesymmetry/react-native-track-player/pull/1482

**Comment by nicopaez** [comment] 2022-06-01 14:09
Hi, I am having this issue with Android and beyond the repeat mode.

Actual behavior:
1. I initialize the TrackPlayer (setupPlayer)
2. Then I subscribe to the "playback-track-changed" event
3. I add a track to the Player, then the event is fired twice
4. When the track changes, the event is fired but in some occasions (random) the is fired twice

Expected behavior:
1. When the trackPlayer is created (or reseted) and a track is added, the event is fired once
2. When the trackPlayer is playing and the current track changes, the event is fired once


**Environment**:
TrackPlayer version: 2.1.3
React-Native version: 0.67.3
Android Emulator Device: Google Pixel 3a API 30, Android 11.0 Google Play.

**Comment by jspizziri** [comment] 2022-07-20 15:45
fixed via https://github.com/doublesymmetry/react-native-track-player/pull/1501

**Closed by jspizziri** 2022-07-20 15:45 UTC
Labels: Bug, Platform: iOS

**Comment by Tanvirazad3449** [comment] 2022-09-15 21:40
Hello, I am using 2.1.3 of React Native Track Player and the event PlaybackTrackChanged is firing numerous times for a single track. Has this issue been completely solved?

**Comment by trm217** [comment] 2022-10-13 15:33
The most problematic thing about this event is the fact that it‘s both unpredictable and inconsistent between platforms.

I have an update logic based on the queue advancing, that due to the lack for a better api, I must solve by observing Event.PlaybackTrackChange and calling TrackPlayer.getCurrentTrack in it. To then execute the logic, I must compare the result to a ref of the last call to that handler. 

It's a giant mess and gets even messier, when I have to reset the queue due to the user rearranging the items in the app.

Now with that working I then run into the new issues due to android and ios having different occurrences of this event.
 
This all would've been so much easier if we just had hooks to receive the current track and the queue.

Perhaps eventually I'll try to contribute to this repo myself, however until then, I must first find a way to get this working with the current APIs (have been on it for quite a bit 😦)
