### ISSUE TITLE
remove function is not working

### ISSUE THREAD

**Issue by jindao** [doublesymmetry/react-native-track-player#1442] opened 2022-03-22 10:36 UTC
I'm using "react-native-track-player": "^2.1.2".

import TrackPlayer from 'react-native-track-player';
...

await TrackPlayer.add(track);
...
await TrackPlayer.remove(0); 

0 is track index.
this code is not working.
I want to remove first track queued .

If i'm wrong or you have good solution, please let me know.

Thanks

**Comment by barbogast** [comment] 2022-04-09 14:05
Looks like remove the current track is not supported: https://github.com/doublesymmetry/react-native-track-player/blob/main/ios/RNTrackPlayer/RNTrackPlayer.swift#L358

Maybe that's the reason?

**Comment by dcvz** [comment] 2022-04-12 21:04
We do not allow you to remove the currently playing track. Closing as this is not a bug and intended behaviour.

**Closed by dcvz** 2022-04-12 21:04 UTC
Labels: Bug
