### ISSUE TITLE
[Android] Crash Fatal Exception: android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent 

### ISSUE THREAD

**Issue by RamProg** [doublesymmetry/react-native-track-player#1812] opened 2022-11-07 09:49 UTC
**Describe the Bug**
I have reports of consistent crashes on production. I haven't been able to reproduce it.

**Steps To Reproduce**
```
Fatal Exception: android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent { cmp=com.charmander.pikachu/com.doublesymmetry.trackplayer.service.MusicService }: app is in background uid UidRecord{46d20f0 u0a331 TPSL idle procs:0 seq(0,0,0)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1941)
       at android.app.ContextImpl.startService(ContextImpl.java:1887)
       at android.content.ContextWrapper.startService(ContextWrapper.java:793)
       at android.content.ContextWrapper.startService(ContextWrapper.java:793)
       at com.doublesymmetry.trackplayer.module.MusicModule.setupPlayer(MusicModule.java:184)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
       at java.lang.Thread.run(Thread.java:920)
```

**Code To Reproduce**
It started happening when updating to 3.0.0.
In 100% of the cases this happens the app is in the background.

**Replicable on Example App?**
Not able to do this at the moment.

**Environment Info:**
Not happening on local, only production in several different devices, specially HUAWEI.
`react-native-track-player 3.2.0-d23c3fb990aaf9d6783881fabe21e059b62b0782`

**How I can Help**
Here to help however I can.

**Comment by RamProg** [comment] 2022-11-24 13:57
Any ideas guys?

**Comment by puckey** [comment] 2022-11-24 14:40
Can you list the device models experiencing crashes?

**Comment by elliotdickison** [comment] 2022-11-26 19:14
I'm experiencing this in production as well. In my case it appears to be the result of Android restarting my app in the background which causes `setupPlayer` to be called in the background which blows everything up. Here's my stack trace:

```
android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent { cmp=com.maz.combo3310/com.doublesymmetry.trackplayer.service.MusicService }: app is in background uid UidRecord{c2dfd2 u0a43 TRNB idle change:procadj procs:0 seq(12131417,12131364)}
    at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1908)
    at android.app.ContextImpl.startService(ContextImpl.java:1864)
    at android.content.ContextWrapper.startService(ContextWrapper.java:817)
    at android.content.ContextWrapper.startService(ContextWrapper.java:817)
    at com.doublesymmetry.trackplayer.module.MusicModule.setupPlayer(MusicModule.kt:184)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
    at com.facebook.jni.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
    at java.lang.Thread.run(Thread.java:1012)
```

Occurring on SDK 31+ (which makes sense: https://developer.android.com/about/versions/12/behavior-changes-12#foreground-service-launch-restrictions).

I am going to attempt some JavaScript-land workarounds to delay calling `setupPlayer` until the app enters the foreground. Will report back with results.

**Comment by quentingirard** [comment] 2022-11-28 08:22
Hello guys, I'm facing the same issue with **SDK31** and react-native-track-player **v.2.1.3**

```
Exception android.app.BackgroundServiceStartNotAllowedException:
  at android.app.ContextImpl.startServiceCommon (ContextImpl.java:1941)
  at android.app.ContextImpl.startService (ContextImpl.java:1887)
  at android.content.ContextWrapper.startService (ContextWrapper.java:793)
  at android.content.ContextWrapper.startService (ContextWrapper.java:793)
  at com.guichaguri.trackplayer.module.MusicModule.waitForConnection (MusicModule.java:108)
  at com.guichaguri.trackplayer.module.MusicModule.play (MusicModule.java:330)
  at java.lang.reflect.Method.invoke
  at com.facebook.react.bridge.JavaMethodWrapper.invoke (JavaMethodWrapper.java:372)
  at com.facebook.react.bridge.JavaModuleWrapper.invoke (JavaModuleWrapper.java:188)
  at com.facebook.react.bridge.queue.NativeRunnable.run
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage (MessageQueueThreadHandler.java:27)
  at android.os.Looper.loopOnce (Looper.java:226)
  at android.os.Looper.loop (Looper.java:313)
  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run (MessageQueueThreadImpl.java:226)
  at java.lang.Thread.run (Thread.java:1012)
```

On these devices

![image](https://user-images.githubusercontent.com/15869493/204228006-bd1cad6a-af8f-4e01-b4ca-617b6eb48a55.png)

I hope it could help !

**Comment by elliotdickison** [comment] 2022-11-29 21:10
> I am going to attempt some JavaScript-land workarounds to delay calling setupPlayer until the app enters the foreground. Will report back with results.

I did this and I'm no longer getting errors related to attempting setup in the background. Here's what I'm getting now though: 

```
Exception android.app.ForegroundServiceStartNotAllowedException:
  at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel (ForegroundServiceStartNotAllowedException.java:54)
  at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel (ForegroundServiceStartNotAllowedException.java:50)
  at android.os.Parcel.readParcelable (Parcel.java:3346)
  at android.os.Parcel.createExceptionOrNull (Parcel.java:2433)
  at android.os.Parcel.createException (Parcel.java:2422)
  at android.os.Parcel.readException (Parcel.java:2405)
  at android.os.Parcel.readException (Parcel.java:2347)
  at android.app.IActivityManager$Stub$Proxy.setServiceForeground (IActivityManager.java:8095)
  at android.app.Service.startForeground (Service.java:733)
  at com.doublesymmetry.trackplayer.service.MusicService$observeEvents$4$1.emit (MusicService.kt:392)
  at com.doublesymmetry.trackplayer.service.MusicService$observeEvents$4$1.emit (MusicService.kt:389)
  at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl (SharedFlow.kt:383)
  at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:106)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loopOnce (Looper.java:226)
  at android.os.Looper.loop (Looper.java:313)
  at android.app.ActivityThread.main (ActivityThread.java:8751)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:571)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1135)
Caused by android.os.RemoteException: Remote stack trace:
  at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked (ActiveServices.java:1955)
  at com.android.server.am.ActiveServices.setServiceForegroundLocked (ActiveServices.java:1455)
  at com.android.server.am.ActivityManagerService.setServiceForeground (ActivityManagerService.java:14155)
  at android.app.IActivityManager$Stub.onTransact (IActivityManager.java:3648)
  at com.android.server.am.ActivityManagerService.onTransact (ActivityManagerService.java:3036)
```

Has occurred on Android SDK 31 & 33 on the following devices:
- google crosshatch
- google oriole
- samsung a03s
- samsung g0q
- samsung r8q

**Comment by MissingCorner-HaoPhan** [comment] 2023-03-16 02:05
I am in version 2.1.4, and i have same error: 
`Fatal Exception: android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent { cmp=com.missingcorner.calmkids/com.guichaguri.trackplayer.service.MusicService }: app is in background uid UidRecord{db93d2a u0a7052 TPSL idle change:cached|procstate procs:0 seq(16716715,16716137)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1981)
       at android.app.ContextImpl.startService(ContextImpl.java:1927)
       at android.content.ContextWrapper.startService(ContextWrapper.java:834)
       at android.content.ContextWrapper.startService(ContextWrapper.java:834)
       at com.guichaguri.trackplayer.module.MusicModule.waitForConnection(MusicModule.java:29)
       at com.guichaguri.trackplayer.module.MusicModule.getTrack(MusicModule.java:5)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:148)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:21)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:37)
       at java.lang.Thread.run(Thread.java:1012)`

**Comment by ghiculescualexandru** [comment] 2023-03-17 07:47
Is there any update on this one? I'm getting numerous crashes in production, even though nothing changed regarding my usage of RNTP.

**Comment by ramazanarslan** [comment] 2023-03-20 10:09
i am still getting this error.  
 ```
"react-native": "0.71.3",
 "react-native-track-player": "^3.2.0-bb749e5d286737681ba8907dfd287480eb1cec45",

```
<img width="409" alt="image" src="https://user-images.githubusercontent.com/31334024/226308739-4196e1ac-be5c-4452-a707-c55fa23675d5.png">

```
Fatal Exception: android.app.BackgroundServiceStartNotAllowedException
Not allowed to start service Intent { cmp=com.biryudumkitap/com.doublesymmetry.trackplayer.service.MusicService }: app is in background uid UidRecord{4ede2b9 u0a325 TPSL idle procs:0 seq(0,0,0)}
```

**Comment by puckey** [comment] 2023-03-28 14:53
rc03 should provide a fix for this crash: https://github.com/doublesymmetry/react-native-track-player/releases/tag/v4.0.0-rc03

TrackPlayer.setupPlayer(options) now rejects when it was called in the background on Android. In the background app we are retrying automatically when the app comes back to the foreground in this case, but you could also choose to throw up a retry button or something else: https://github.com/doublesymmetry/react-native-track-player/blob/main/example/src/services/SetupService.ts#L17-L22

Please test to see if this fixes things for you – if it does not I will reopen the issue.

**Closed by puckey** 2023-03-28 14:53 UTC
Labels: Bug, Platform: Android

**Comment by daviluisb** [comment] 2023-03-31 21:19
@puckey I'im currently using the "react-native-track-player": "^3.2.0-09a5592daec94a703c93c8d3e59beeaa430360fe", which is the @nightly version with all upgrades, im logging a error returned by calling TrackPlayer.reset in background and this is the stacktrace.

Fatal Exception: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service com.app/com.doublesymmetry.trackplayer.service.MusicService
       at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
       at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
       at android.os.Parcel.readParcelable(Parcel.java:3346)
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2433)
       at android.os.Parcel.createException(Parcel.java:2422)
       at android.os.Parcel.readException(Parcel.java:2405)
       at android.os.Parcel.readException(Parcel.java:2347)
       at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:8063)
       at android.app.Service.startForeground(Service.java:733)
       at com.doublesymmetry.trackplayer.service.MusicService$observeEvents$4$1.emit(MusicService.kt:510)
       at com.doublesymmetry.trackplayer.service.MusicService$observeEvents$4$1.emit(MusicService.kt:507)
       at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:383)
       at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(:15)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8663)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
       
       Caused by android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:1955)
	at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:1455)
	at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:14127)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3641)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3032)

**Comment by puckey** [comment] 2023-04-01 08:10
@daviluisb please create a new issue with some more information on how to reproduce
