### ISSUE TITLE
iOS silent mode no sound when providing iosCategoryOptions (v2.1.0)

### ISSUE THREAD

**Issue by dimadeveatii** [doublesymmetry/react-native-track-player#1281] opened 2021-09-24 07:09 UTC
**Describe the bug**
After an upgrade from `v1.2.7` to `2.1.0` the audio is affected on iOS by the hardware "silent mode" switch. When the "silent mode" is off, the audio plays, but as soon the the switched is turned on the audio is silenced.  
We use the following setup:
```ts
const metadataOptions = {
  capabilities: [
      Capability.Play,
      Capability.Pause,
      Capability.SeekTo,
      Capability.JumpBackward,
      Capability.JumpForward,
  ],
  stopWithApp: isAndroid(),
  compactCapabilities: [Capability.Play, Capability.Pause],
};

const playerOptions: PlayerOptions = {
  iosCategory: IOSCategory.Playback,
  iosCategoryOptions: [
      IOSCategoryOptions.InterruptSpokenAudioAndMixWithOthers,
      IOSCategoryOptions.DuckOthers,
      IOSCategoryOptions.AllowAirPlay,
      IOSCategoryOptions.AllowBluetooth,
      IOSCategoryOptions.AllowBluetoothA2DP,
  ],
  iosCategoryMode: IOSCategoryMode.Default,
};

TrackPlayer.setupPlayer(playerOptions)
  .then(() => TrackPlayer.updateOptions(metadataOptions));
```
It seems like there was a similar problem in an older version, mentioned in https://github.com/DoubleSymmetry/react-native-track-player/issues/1145.  
One workaround is to provide an empty `iosCategoryOptions` array - that fixes the problem and then the audio plays with sound while the device is on "silent mode". However, we need to provide those options.

**To Reproduce**
- Setup the player with a non-empty `iosCategoryOptions` 
- Play a sound file (either local or http) with `TrackPlayer.play()` on an iPhone device
- Switch ON the device hardware "silent mode"
- When the device silent mode is enabled, the audio plays with no sound.

**Environment (please complete the following information):**
Run `react-native info` in your project and share the content.
```sh
System:
    OS: macOS 11.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 5.44 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.8.0 - /var/folders/s5/7qt82swx01ld35kjs2tg9ff40000gn/T/yarn--1632467023270-0.7584884053647847/node
    Yarn: 1.22.11 - /var/folders/s5/7qt82swx01ld35kjs2tg9ff40000gn/T/yarn--1632467023270-0.7584884053647847/yarn
    npm: 7.24.0 - /usr/local/bin/npm
    Watchman: 2021.08.23.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 23, 29, 31
      Build Tools: 29.0.2, 31.0.0
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7621141
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

What `react-native-track-player` version are you using?
- v2.1.0 

Are you testing on a real device or in the simulator? Which OS version are you running?
- Running on a real device, iOS 15

**Code**
The setup code from above.

**Comment by MatthiasDh** [comment] 2021-09-24 13:06
Having the same issue

**Comment by uzegonemad** [comment] 2021-09-24 23:17
You can handle this natively in `AppDelegate.m`.

1. Import AVFoundation
```#import <AVFoundation/AVFoundation.h>```

2. Add this to the end of your `didFinishLaunchingWithOptions` function, right before the `return YES;`

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  //...
  // Allow audio to play when phone is muted
  [[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayback error: nil];
  return YES;
}
```

**Comment by dimadeveatii** [comment] 2021-09-27 06:16
Thanks @uzegonemad !
I can confirm that works and fixes the issue.  

It would still be nice to be able to set that via options in `react-native-track-player`.

**Comment by charneykaye** [comment] 2022-01-06 19:48
I apologize if this is an amateur iOS problem, but I'm trying to perform @uzegonemad fix and hit [this problem which I posted on stackoverflow](https://stackoverflow.com/questions/70612619/ios-app-build-fails-with-undeclared-identifier-avaudiosession)

**Comment by bradleyflood** [comment] 2022-01-15 10:46
@uzegonemad Thanks for that fix. Is this something you could add back in to RNTP by a PR? 

Please and thanks :)

**Comment by jspizziri** [comment] 2022-04-30 10:33
@dimadeveatii 

I just tested this against `main` and I was unable to reproduce based on your instructions. I'm wondering if it already got fixed by [the work here](https://github.com/doublesymmetry/react-native-track-player/commit/0dc7f86b8c18910abd72c6cc4d12951ad366d870) and the underlying upgrade to `SwiftAudioEx`. I'm going to close this issue for now, but if you find a way to reproduce it in `2.2.0-rc3` let me know and I'll reopen it.

**Closed by jspizziri** 2022-04-30 10:33 UTC
Labels: Bug, Platform: iOS

**Comment by puckey** [comment] 2022-05-06 18:43
@jspizziri While I was also experiencing muted sound when providing iosCategoryOptions in `2.2.0-rc3`, using the current main branch fixed things.. time for a new rc?

**Comment by jspizziri** [comment] 2022-05-06 19:05
@puckey I'm not sure what the ETA on the next RC is. I'm guessing the goal is that it would contain the big android fix. I'll let @dcvz weigh in on the timeline if he's able.

**Comment by dimadeveatii** [comment] 2022-11-10 12:51
@jspizziri we've just updated to v3.2.0 and I can confirm this now properly works without any workarounds. 
It has been fixed 🙌 !
