### ISSUE TITLE
Fatal Exception: kotlin.UninitializedPropertyAccessException

### ISSUE THREAD

**Issue by Vietvantue** [doublesymmetry/react-native-track-player#1639] opened 2022-08-10 08:50 UTC
**Describe the Bug**
App crash while using react-native-track-player

**Steps To Reproduce**

**Code To Reproduce**
```
TrackPlayer.reset();
TrackPlayer.add([sound1, sound2]);
TrackPlayer.play();
```

**Environment Info:**
react-native: 0.68.2
react-native-track-player: ^2.2.0-rc4
Device: Samsung A8 Tablet
OS: Android

**Crashlytics log**
```
Fatal Exception: kotlin.UninitializedPropertyAccessException: lateinit property descriptionAdapter has not been initialized
       at com.doublesymmetry.kotlinaudio.notification.NotificationManager$destroy$1.invokeSuspend(NotificationManager.kt:295)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:247)
       at android.app.ActivityThread.main(ActivityThread.java:8676)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by jspizziri** [comment] 2022-08-11 09:45
Can you reproduce this in the example app? I would be very surprised if this wasn't working there.

**Comment by jspizziri** [comment] 2022-08-13 10:52
Closing due to lack of feedback.

**Comment by OlehRiepkin** [comment] 2022-08-18 09:52
Have similar issue. Looks like it happens in background when proximity mode is on (according to Firebase Crashlytics).

"react-native": "0.69.1"
"react-native-track-player": "^3.0.0"

Device: Galaxy A12 (Android 11)

**Firebase logs**

```
Fatal Exception: java.lang.RuntimeException
Unable to stop service com.doublesymmetry.trackplayer.service.MusicService@1d2f0b0: kotlin.UninitializedPropertyAccessException: lateinit property player has not been initialized

Fatal Exception: java.lang.RuntimeException: Unable to stop service com.doublesymmetry.trackplayer.service.MusicService@1d2f0b0: kotlin.UninitializedPropertyAccessException: lateinit property player has not been initialized
       at android.app.ActivityThread.handleStopService(ActivityThread.java:4844)
       at android.app.ActivityThread.access$2100(ActivityThread.java:301)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2220)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8653)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

```
Caused by kotlin.UninitializedPropertyAccessException
lateinit property player has not been initialized

Caused by kotlin.UninitializedPropertyAccessException: lateinit property player has not been initialized
       at com.doublesymmetry.trackplayer.service.MusicService.stopPlayer(MusicService.kt:234)
       at com.doublesymmetry.trackplayer.service.MusicService.onDestroy(MusicService.kt:488)
       at android.app.ActivityThread.handleStopService(ActivityThread.java:4824)
       at android.app.ActivityThread.access$2100(ActivityThread.java:301)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2220)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8653)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by Vietvantue** [comment] 2022-08-18 14:44
@OlehRiepkin Although we have the same symptom, I doubt they are in the same location. However, according to the Crashlytics log, this is due to kotlin's late init variable.
```
Caused by kotlin.UninitializedPropertyAccessException
lateinit property player has not been initialized
```

**Comment by mvrty** [comment] 2022-08-23 14:25
Not sure if this is related but getting crashes (randomly - works most time) when initing track player (using `await TrackPlayer.setupPlayer()`)
RN 0.69.4
Track Player 3.1.0

Happening on both device and emulator (Pixel 6 (api 31), emulator (api 31), emulator (api 30))

Generates two crash reports in Flipper:
(first)
```FATAL EXCEPTION: main

Unknown

FATAL EXCEPTION: main
Process: com.newglobal, PID: 10477
java.lang.IllegalStateException: Another SimpleCache instance uses the folder: /data/user/0/com.xxx/cache/TrackPlayer
	at com.google.android.exoplayer2.upstream.cache.SimpleCache.<init>(SimpleCache.java:249)
	at com.google.android.exoplayer2.upstream.cache.SimpleCache.<init>(SimpleCache.java:229)
	at com.google.android.exoplayer2.upstream.cache.SimpleCache.<init>(SimpleCache.java:194)
	at com.doublesymmetry.kotlinaudio.players.BaseAudioPlayer.<init>(BaseAudioPlayer.kt:140)
	at com.doublesymmetry.kotlinaudio.players.QueuedAudioPlayer.<init>(QueuedAudioPlayer.kt:14)
	at com.doublesymmetry.trackplayer.service.MusicService.setupPlayer(MusicService.kt:81)
	at com.doublesymmetry.trackplayer.module.MusicModule$onServiceConnected$1.invokeSuspend(MusicModule.kt:56)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@de170e2, Dispatchers.Main]
```

(second)
```FATAL EXCEPTION: main

java.lang.RuntimeException: Unable to stop service com.doublesymmetry.trackplayer.service.MusicService@f60a40e: kotlin.UninitializedPropertyAccessException: lateinit property player has not been initialized

FATAL EXCEPTION: main
Process: com.newglobal, PID: 10670
java.lang.RuntimeException: Unable to stop service com.doublesymmetry.trackplayer.service.MusicService@f60a40e: kotlin.UninitializedPropertyAccessException: lateinit property player has not been initialized
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4375)
	at android.app.ActivityThread.access$1900(ActivityThread.java:237)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1956)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property player has not been initialized
	at com.doublesymmetry.trackplayer.service.MusicService.onDestroy(MusicService.kt:471)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:4355)
	... 8 more
```

**Comment by zzorba** [comment] 2022-08-27 15:44
Seeing the same thing, on 69.4 + 3.1.0

**Comment by jspizziri** [comment] 2022-08-27 15:47
Is this an issue only in RN 0.69? Or is someone able to reproduce this in the example project which is running 0.68 (I believe)

**Comment by zzorba** [comment] 2022-08-27 17:17
So far I have not able to reproduce it on a simulator (as is the case for most Android bugs I experience), but I'm seeing a large number of crashes being reported to AppCenter, and it matches the upgrade from 2.2.0-rc4 to 3.1.0.

```
com.doublesymmetry.trackplayer.service.MusicService.onDestroy MusicService.kt:471
android.app.ActivityThread.handleStopService ActivityThread.java:4694
android.app.ActivityThread.access$3000 ActivityThread.java:296
android.app.ActivityThread$H.handleMessage ActivityThread.java:2264
android.os.Handler.dispatchMessage Handler.java:107
android.os.Looper.loop Looper.java:213
android.app.ActivityThread.main ActivityThread.java:8178
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:513
com.android.internal.os.ZygoteInit.main ZygoteInit.java:1101
```

I haven't received any actual complaints from users though, so I suspect it might be a background crash?   

Going to attempt reverting back to 2.2.0-rc4 (which I was using previously) in an attempt to confirm this is indeed upgrade related.

**Comment by zzorba** [comment] 2022-08-29 19:13
Update: rolling my release back to RTP 2.2.0-rc4 seems to have eliminated this crash.  I still haven't been able to get a working reproduction on a simulator, and based on crash telemetry it doesn't seem to be related to a specific android version.

**Comment by andrewdazs** [comment] 2022-08-29 20:48
I'm using RN 65.2 + Track Player 3.1.0 and also facing this crash. It happened once with the app opened and other times with the app in background.

```
FATAL EXCEPTION: main

java.lang.RuntimeException: Unable to stop service com.doublesymmetry.trackplayer.service.MusicService@bb7f5f0: kotlin.UninitializedPropertyAccessException: lateinit property player has not been initialized
```

@mvrty when you stopped using `await` with `.setupPlayer()` the crashes gone?

**Comment by mvrty** [comment] 2022-08-30 08:01
It seem to be cache naming conflict with Exoplayer? https://github.com/doublesymmetry/KotlinAudio/issues/9

These crashed only happened on bundle reload for me (either via reloading from metro or using React Native Restart - we're using restart to accurately set RTL/LTR mode for languages). Just initialising cache to null removed all crashes for me but not sure what else that might effect - solution is probably to change cacheDir name in KotlinAudio (above linked issue)?

If you want to try temporarily, change line 81 in `MusicService.kt` to 
```
player = QueuedAudioPlayer(this@MusicService, bufferOptions, null)
```

**Comment by rborn** [comment] 2022-08-31 13:35
@jspizziri I can confirm this works and that on reload I have the crashes too.  
Version 3.1.0

I tried to  modify the cacheConfig but my kotlin knowledge is -100 and cannot even make it compile with my changes  😅

**Comment by jspizziri** [comment] 2022-08-31 15:05
@mvrty @rborn 

So you both are saying that you're using multiple versions of ExoPlayer and that's what's causing this issue? Do you have a way to reliably reproduce it?

**Comment by zzorba** [comment] 2022-08-31 15:43
I don't have a second version of ExoPlayer that I'm aware of (no other audio/video stuff besides this library) but would it be an issue if a user upgraded from a previous version (and had an old cache folder sitting around on their device?)

**Comment by jspizziri** [comment] 2022-08-31 15:51
@mpivchev do you have any ideas on how caching in KotlinAudio/ExoPlayer might be at play here?

**Comment by mvrty** [comment] 2022-08-31 16:09
@jspizziri Not using multiple versions here either. On a fresh android emulator the example app in this repo crashes on a bundle reload from metro here (does it work on yours?) - no crashes when passing `null` as `cacheOptions` in `MusicService.kt`

**Comment by jspizziri** [comment] 2022-08-31 16:34
@mvrty , when you say a bundle reload, do you mean when you trigger a JS reload?

**Comment by mvrty** [comment] 2022-08-31 16:47
Yes, sorry for being unclear.

**Comment by rborn** [comment] 2022-08-31 16:50
@jspizziri I don't have multiple versions, I'm upgrading the module from an old 2.x version and this shows in a clean andorid 13 emulator.
If a hot reload triggers ( Sometimes in my case it will fully reload the app, not only a specific file) the app crashes with this

~~~
08-31 18:44:50.325  4562  4562 E AndroidRuntime: FATAL EXCEPTION: main
08-31 18:44:50.325  4562  4562 E AndroidRuntime: Process: com.letsemjoy.app, PID: 4562
08-31 18:44:50.325  4562  4562 E AndroidRuntime: java.lang.IllegalStateException: Another SimpleCache instance uses the folder: /data/user/0/com.letsemjoy.app/cache/TrackPlayer
08-31 18:44:50.325  4562  4562 E AndroidRuntime: 	at com.google.android.exoplayer2.upstream.cache.SimpleCache.<init>(SimpleCache.java:249)
08-31 18:44:50.325  4562  4562 E AndroidRuntime: 	at com.google.android.exoplayer2.upstream.cache.SimpleCache.<init>(SimpleCache.java:229)
08-31 18:44:50.325  4562  4562 E AndroidRuntime: 	at com.google.android.exoplayer2.upstream.cache.SimpleCache.<init>(SimpleCache.java:194)
08-31 18:44:50.325  4562  4562 E AndroidRuntime: 	at com.doublesymmetry.kotlinaudio.players.BaseAudioPlayer.<init>(BaseAudioPlayer.kt:140)
08-31 18:44:50.325  4562  4562 E AndroidRuntime: 	at com.doublesymmetry.kotlinaudio.players.QueuedAudioPlayer.<init>(QueuedAudioPlayer.kt:14)
08-31 18:44:50.325  4562  4562 E AndroidRuntime: 	at com.doublesymmetry.trackplayer.service.MusicService.setupPlayer(MusicService.kt:81)
08-31 18:44:50.325  4562  4562 E AndroidRuntime: 	at com.doublesymmetry.trackplayer.module.MusicModule$onServiceConnected$1.invokeSuspend(MusicModule.kt:56)
08-31 18:44:50.325  4562  4562 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
08-31 18:44:50.325  4562  4562 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
08-31 18:44:50.325  4562  4562 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
08-31 18:44:50.325  4562  4562 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
08-31 18:44:50.325  4562  4562 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
08-31 18:44:50.325  4562  4562 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
08-31 18:44:50.325  4562  4562 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7898)
08-31 18:44:50.325  4562  4562 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-31 18:44:50.325  4562  4562 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
08-31 18:44:50.325  4562  4562 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
08-31 18:44:50.325  4562  4562 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@38e8365, Dispatchers.Main]
08-31 18:44:50.366   589  4966 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
~~~

After I did the change suggested by @mvrty I still have  it from time to time, but very rare.

**Comment by rborn** [comment] 2022-09-05 11:02
I think I was commenting in the wrong issue 😅 https://github.com/doublesymmetry/react-native-track-player/issues/1633#issuecomment-1235316807 But I think I have a fix for this.

I will paste here the patch file  if anyone wants to test -  I don't get any more crashes with this error `UninitializedPropertyAccessException` (I still get the ones with `SimpleCache`)



```
diff --git a/node_modules/react-native-track-player/android/src/main/java/com/doublesymmetry/trackplayer/service/MusicService.kt b/node_modules/react-native-track-player/android/src/main/java/com/doublesymmetry/trackplayer/service/MusicService.kt
index 776d260..9e9f31d 100644
--- a/node_modules/react-native-track-player/android/src/main/java/com/doublesymmetry/trackplayer/service/MusicService.kt
+++ b/node_modules/react-native-track-player/android/src/main/java/com/doublesymmetry/trackplayer/service/MusicService.kt
@@ -455,7 +455,7 @@ class MusicService : HeadlessJsTaskService() {
     override fun onTaskRemoved(rootIntent: Intent?) {
         super.onTaskRemoved(rootIntent)
 
-        if (stoppingAppPausesPlayback) {
+        if (stoppingAppPausesPlayback && this::player.isInitialized ) {
             player.pause()        
         }
     }
@@ -468,7 +468,9 @@ class MusicService : HeadlessJsTaskService() {
     @MainThread
     override fun onDestroy() {
         super.onDestroy()
-        player.stop()
+        if (this::player.isInitialized ) {
+            player.stop()
+        }
     }
 
     @MainThread




```

**Comment by rborn** [comment] 2022-09-05 12:59
Looks like somebody did a PR with this already: https://github.com/doublesymmetry/react-native-track-player/issues/1699

**Comment by jspizziri** [comment] 2022-09-06 15:05
All please test #1700 via the nightly build, and let us know if the problem persists.

**Closed by jspizziri** 2022-09-06 15:05 UTC
Labels: Bug, Platform: Android, Needs Feedback

**Comment by jspizziri** [comment] 2022-09-06 15:07
All, there was a PR merged that it sounds like addresses this issue:

https://github.com/doublesymmetry/react-native-track-player/pull/1700

Please let me know if I'm wrong about that.
