### ISSUE TITLE
Initial 'TrackPlayer.play()' doesn't updates remote state - iOS Control Center

### ISSUE THREAD

**Issue by paulinosantos** [DoubleSymmetry/react-native-track-player#209] opened 2018-05-31 02:36 UTC
Hi! I am seeing that when the audio initially starts playing after the player has been setup the 'play' music control doesn't changes to the 'pause' button. After clicking the 'play' button once over in the control center then remote events are catched accordingly and I can handle them alright. The expected behavior would be to get the music control play button to automatically switch to the 'pause' icon at the first `TrackPlayer.play()` performed. Just in case I've added my code below. Any help is greatly appreciated.

```
export default class Player extends Component {

    STREAM_URL = 'http://s4.streammonster.com:port';

    setupPlayer() {
        TrackPlayer.setupPlayer().then(async () => {
            TrackPlayer.updateOptions({
                capabilities: [
                    TrackPlayer.CAPABILITY_PLAY,
                    TrackPlayer.CAPABILITY_PAUSE],
                stopWithApp: true,
                color: 0x2ecc71
            });

            // Adds a track to the queue
            await TrackPlayer.add({
                id: 'trackId',
                url: this.STREAM_URL,
                title: 'Track Title',
                artist: 'Track Artist',

            });
            // Starts playing it
            Player.play();

        });
    }

    static play() {
        TrackPlayer.play();
    }

    static pause() {
        TrackPlayer.pause();
    }

    render() {
        //Setup Player first
        this.setupPlayer();


        return (
            <View style={styles.container}>
                <Text style={styles.welcome}>
                    ¡Test App!
        </Text>
                <Image
                    style={styles.logo}
                    source={require('../../assets/logo.png')}
                />
            </View>
        );
    }


}

```

**Comment by ishigamii** [comment] 2019-03-19 10:39
@paulinosantos  do you still have the issue with new version ? if not can you close the issue ?

**Comment by cylwin** [comment] 2019-04-20 20:05
Same problem here.

**Comment by curiousdustin** [comment] 2020-04-26 18:45
@cylwin @mauriziocarella @paulinosantos what version are you having this issue on?

**Comment by fernando-pascoal** [comment] 2020-08-15 12:54
@paulinosantos 
which version are you using? I recommend you use version ^ 1.2.3. How is your services.js?

Before opening an issue, this information must be entered.

**Comment by dcvz** [comment] 2021-08-10 16:36
Closing due to inactivity, and cannot reproduce this on v2.

**Closed by dcvz** 2021-08-10 16:36 UTC
Labels: iOS
