### ISSUE TITLE
App get crash while initialising the Track Player 

### ISSUE THREAD

**Issue by arjundalal** [doublesymmetry/react-native-track-player#1321] opened 2021-10-31 07:14 UTC
Hello Team,
I am using **react-native-track-player** and **react-native-video** into my project. The version of my library are:-
**react-native-video:- ** 5.2.0
**react-native-track-player:- ** 2.1.2
but when i initialise the track player app get crash.
I am assuming that the expoPlayer version of **react-native-track-player** and **react-native-video** getting mismatch.

**I am getting the below error at the time of crash:-**

<img width="958" alt="track1Issue" src="https://user-images.githubusercontent.com/54262572/139572553-484fb714-589f-4d1c-8f48-40fa05a25cc6.png">

Can any one help me to fix this issue.
Thanks in advance

**Comment by nateshmbhat** [comment] 2021-10-31 10:14
Facing same issue

**Comment by coneforapine** [comment] 2021-11-05 15:54
If you manually linked react-native-video just unlink it and let the react-native automatically link it. I solved it by simply unlinking react-native-video manually.

**Comment by arjundalal** [comment] 2021-11-08 05:20
I have tried this solution but it dose not work.
I have remove react-native-video library but still same error occured.

**Comment by Fairbrook** [comment] 2021-11-24 04:51
If you are still facing this issue, maybe this solution will help
[https://github.com/DoubleSymmetry/react-native-track-player/issues/1314#issuecomment-977531114](https://github.com/DoubleSymmetry/react-native-track-player/issues/1314#issuecomment-977531114)

**Comment by nateshmbhat** [comment] 2021-11-26 07:32
I have completely removed the react-native-library itself from the project. but still the crash occurs with the above message.

**Comment by nateshmbhat** [comment] 2021-11-26 16:39
The following seems to be the root cause of this issue. Google's maven repository doesn't contain exo player version `2.11.4` which is being specified by the track player. 
source : [google maven exoplayer](https://maven.google.com/web/index.html?q=com.google.android.ex#com.google.android.exoplayer:exoplayer-core
)

So when gradle builds the app, it might have fetched some other version and that version doesn't have setAttributes method on the SimpleExoPlayer class since this class (or some of its methods) are deprecated or removed in later versions. 

When track player's code would be using some other versions of exo player and this would cause it to crash since this new version has different set of apis to be used.

**Comment by nateshmbhat** [comment] 2021-11-28 08:52
Found a fix for this issue : 

In your project build.gradle file , add the following inside the block `all projects -> repositories` : 

```
 repositories {
        jcenter() {
            content {
                includeGroup("com.google.android.exoplayer")
            }
        }

        ...
```

And in your app/build.gradle file  , add the following code at the end of the file : 
```
configurations.all {
    resolutionStrategy {
        force 'com.google.android.exoplayer:exoplayer-core:2.11.4'
    }
}

```

**Comment by pybuche** [comment] 2021-12-07 13:14
@nateshmbhat 👋 I have the exact same error but your proposed fix doesn't work for me.

I've tried using these versions:
```
"react-native-track-player": "2.1.2",
"react-native-unimodules": "0.14.6",
"react-native-video": "5.1.1",
```
that both use exoplayer `2.11.4`, yet, the track player works but not the video player. It crashes as soon as I wanna launch the video. 

One weird thing though is that it works perfectly on a simulator (Pixel 3, Android 11), but it crashes instantly on a real device (OnePlus 8T, Android 11).

During build time, the only mention of Exoplayer is here:
```
[13:03:21]: ▸ WARNING: [Processor] Library '/home/circleci/.gradle/caches/modules-2/files-2.1/com.google.android.exoplayer/exoplayer-ui/2.11.4/8be1e4b0aba76de3d8216633c8d9d1625fda2acf/exoplayer-ui-2.11.4.aar' contains references to both AndroidX and old support library. This seems like the library is partially migrated. Jetifier will try to rewrite the library anyway.
```

But I'm not sure this has anything to do with the crash 🤷 Any help would be welcome here!

**Comment by kanzitelli** [comment] 2021-12-10 19:17
Hey @nateshmbhat! Thank you for the these lines:
```
configurations.all {
    resolutionStrategy {
        force 'com.google.android.exoplayer:exoplayer-core:2.11.4'
    }
}
```
I was having problems with making it work with [react-native-appodeal](https://github.com/appodeal/react-native-appodeal) and `force` made it work!

**Comment by kanzitelli** [comment] 2021-12-10 19:25
But I went a bit deeper and tried to make it work with latest [react-native-video](https://github.com/react-native-video/react-native-video) (as it's more often case with rn-track-player) which uses `exoplayer 2.13.2` as can be seen [here](https://github.com/react-native-video/react-native-video/blob/master/android-exoplayer/build.gradle#L31). So I created a patch file which can be used with [patch-package](https://github.com/ds300/patch-package).

Below is the content of the patch file and here is the link to the [gist](https://gist.github.com/kanzitelli/53aca11f6a5d701acf49d0de7c482253):
```
diff --git a/node_modules/react-native-track-player/android/build.gradle b/node_modules/react-native-track-player/android/build.gradle
index a241d94..48138f9 100644
--- a/node_modules/react-native-track-player/android/build.gradle
+++ b/node_modules/react-native-track-player/android/build.gradle
@@ -60,7 +60,7 @@ dependencies {
     //noinspection GradleDynamicVersion
     implementation 'com.facebook.react:react-native:+'
     
-    def exoPlayerVersion = safeExtGet("exoPlayerVersion", '2.11.4')
+    def exoPlayerVersion = safeExtGet("exoPlayerVersion", '2.13.2')
 
     // ExoPlayer Core
     implementation "com.google.android.exoplayer:exoplayer-core:${exoPlayerVersion}"
diff --git a/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/MusicManager.java b/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/MusicManager.java
index 61d17bf..c9969b5 100644
--- a/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/MusicManager.java
+++ b/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/MusicManager.java
@@ -132,8 +132,8 @@ public class MusicManager implements OnAudioFocusChangeListener {
                 .setLoadControl(control)
                 .build();
 
-        player.setAudioAttributes(new com.google.android.exoplayer2.audio.AudioAttributes.Builder()
-                .setContentType(C.CONTENT_TYPE_MUSIC).setUsage(C.USAGE_MEDIA).build());
+        player.getAudioComponent().setAudioAttributes(new com.google.android.exoplayer2.audio.AudioAttributes.Builder()
+                .setContentType(C.CONTENT_TYPE_MUSIC).setUsage((C.USAGE_MEDIA)).build(), false);
 
         return new LocalPlayback(service, this, player, cacheMaxSize, autoUpdateMetadata);
     }
diff --git a/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/player/ExoPlayback.java b/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/player/ExoPlayback.java
index 37a6fbf..8e2d866 100644
--- a/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/player/ExoPlayback.java
+++ b/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/player/ExoPlayback.java
@@ -8,7 +8,7 @@ import com.facebook.react.bridge.Promise;
 import com.google.android.exoplayer2.*;
 import com.google.android.exoplayer2.Player.EventListener;
 import com.google.android.exoplayer2.Timeline.Window;
-import com.google.android.exoplayer2.extractor.mp4.MdtaMetadataEntry;
+import com.google.android.exoplayer2.metadata.mp4.MdtaMetadataEntry;
 import com.google.android.exoplayer2.metadata.Metadata;
 import com.google.android.exoplayer2.metadata.MetadataOutput;
 import com.google.android.exoplayer2.metadata.flac.VorbisComment;
@@ -247,7 +247,7 @@ public abstract class ExoPlayback<T extends Player> implements EventListener, Me
     public void onTimelineChanged(@NonNull Timeline timeline, int reason) {
         Log.d(Utils.LOG, "onTimelineChanged: " + reason);
 
-        if((reason == Player.TIMELINE_CHANGE_REASON_PREPARED || reason == Player.TIMELINE_CHANGE_REASON_DYNAMIC) && !timeline.isEmpty()) {
+        if((reason == Player.TIMELINE_CHANGE_REASON_PLAYLIST_CHANGED || reason == Player.TIMELINE_CHANGE_REASON_SOURCE_UPDATE) && !timeline.isEmpty()) {
             onPositionDiscontinuity(Player.DISCONTINUITY_REASON_INTERNAL);
         }
     }
diff --git a/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/player/SourceMetadata.java b/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/player/SourceMetadata.java
index 069cbbd..725feb9 100644
--- a/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/player/SourceMetadata.java
+++ b/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/player/SourceMetadata.java
@@ -1,6 +1,6 @@
 package com.guichaguri.trackplayer.service.player;
 
-import com.google.android.exoplayer2.extractor.mp4.MdtaMetadataEntry;
+import com.google.android.exoplayer2.metadata.mp4.MdtaMetadataEntry;
 import com.google.android.exoplayer2.metadata.Metadata;
 import com.google.android.exoplayer2.metadata.flac.VorbisComment;
 import com.google.android.exoplayer2.metadata.icy.IcyHeaders;
```

@pybuche this might solve your problem as well :)

if it works well for you guys, I'll create a PR.

**Comment by sadikyalcin** [comment] 2022-01-10 11:11
> But I went a bit deeper and tried to make it work with latest [react-native-video](https://github.com/react-native-video/react-native-video) (as it's more often case with rn-track-player) which uses `exoplayer 2.13.2` as can be seen [here](https://github.com/react-native-video/react-native-video/blob/master/android-exoplayer/build.gradle#L31). So I created a patch file which can be used with [patch-package](https://github.com/ds300/patch-package).
> 
> Below is the content of the patch file and here is the link to the [gist](https://gist.github.com/kanzitelli/53aca11f6a5d701acf49d0de7c482253):
> 
> ```
> diff --git a/node_modules/react-native-track-player/android/build.gradle b/node_modules/react-native-track-player/android/build.gradle
> index a241d94..48138f9 100644
> --- a/node_modules/react-native-track-player/android/build.gradle
> +++ b/node_modules/react-native-track-player/android/build.gradle
> @@ -60,7 +60,7 @@ dependencies {
>      //noinspection GradleDynamicVersion
>      implementation 'com.facebook.react:react-native:+'
>      
> -    def exoPlayerVersion = safeExtGet("exoPlayerVersion", '2.11.4')
> +    def exoPlayerVersion = safeExtGet("exoPlayerVersion", '2.13.2')
>  
>      // ExoPlayer Core
>      implementation "com.google.android.exoplayer:exoplayer-core:${exoPlayerVersion}"
> diff --git a/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/MusicManager.java b/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/MusicManager.java
> index 61d17bf..c9969b5 100644
> --- a/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/MusicManager.java
> +++ b/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/MusicManager.java
> @@ -132,8 +132,8 @@ public class MusicManager implements OnAudioFocusChangeListener {
>                  .setLoadControl(control)
>                  .build();
>  
> -        player.setAudioAttributes(new com.google.android.exoplayer2.audio.AudioAttributes.Builder()
> -                .setContentType(C.CONTENT_TYPE_MUSIC).setUsage(C.USAGE_MEDIA).build());
> +        player.getAudioComponent().setAudioAttributes(new com.google.android.exoplayer2.audio.AudioAttributes.Builder()
> +                .setContentType(C.CONTENT_TYPE_MUSIC).setUsage((C.USAGE_MEDIA)).build(), false);
>  
>          return new LocalPlayback(service, this, player, cacheMaxSize, autoUpdateMetadata);
>      }
> diff --git a/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/player/ExoPlayback.java b/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/player/ExoPlayback.java
> index 37a6fbf..8e2d866 100644
> --- a/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/player/ExoPlayback.java
> +++ b/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/player/ExoPlayback.java
> @@ -8,7 +8,7 @@ import com.facebook.react.bridge.Promise;
>  import com.google.android.exoplayer2.*;
>  import com.google.android.exoplayer2.Player.EventListener;
>  import com.google.android.exoplayer2.Timeline.Window;
> -import com.google.android.exoplayer2.extractor.mp4.MdtaMetadataEntry;
> +import com.google.android.exoplayer2.metadata.mp4.MdtaMetadataEntry;
>  import com.google.android.exoplayer2.metadata.Metadata;
>  import com.google.android.exoplayer2.metadata.MetadataOutput;
>  import com.google.android.exoplayer2.metadata.flac.VorbisComment;
> @@ -247,7 +247,7 @@ public abstract class ExoPlayback<T extends Player> implements EventListener, Me
>      public void onTimelineChanged(@NonNull Timeline timeline, int reason) {
>          Log.d(Utils.LOG, "onTimelineChanged: " + reason);
>  
> -        if((reason == Player.TIMELINE_CHANGE_REASON_PREPARED || reason == Player.TIMELINE_CHANGE_REASON_DYNAMIC) && !timeline.isEmpty()) {
> +        if((reason == Player.TIMELINE_CHANGE_REASON_PLAYLIST_CHANGED || reason == Player.TIMELINE_CHANGE_REASON_SOURCE_UPDATE) && !timeline.isEmpty()) {
>              onPositionDiscontinuity(Player.DISCONTINUITY_REASON_INTERNAL);
>          }
>      }
> diff --git a/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/player/SourceMetadata.java b/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/player/SourceMetadata.java
> index 069cbbd..725feb9 100644
> --- a/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/player/SourceMetadata.java
> +++ b/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/player/SourceMetadata.java
> @@ -1,6 +1,6 @@
>  package com.guichaguri.trackplayer.service.player;
>  
> -import com.google.android.exoplayer2.extractor.mp4.MdtaMetadataEntry;
> +import com.google.android.exoplayer2.metadata.mp4.MdtaMetadataEntry;
>  import com.google.android.exoplayer2.metadata.Metadata;
>  import com.google.android.exoplayer2.metadata.flac.VorbisComment;
>  import com.google.android.exoplayer2.metadata.icy.IcyHeaders;
> ```
> 
> @pybuche this might solve your problem as well :)
> 
> if it works well for you guys, I'll create a PR.

Thanks. I'll make it easier for peeps;

1. Install `patch-package and postinstall` packages: `yarn add patch-package postinstall-postinstall`
2. Create `patches` directory on root and create `react-native-track-player+2.1.2.patch` inside `patches` directory with the above patch.
3. Add `"postinstall": "patch-package"` to the `scripts` block inside `package.json`
4. Run `yarn postinstall` and that should apply the patch(es);

```
patch-package 6.4.7
Applying patches...
react-native-track-player@2.1.2 ✔
```

Each time, you add a new package, the `postinstall` script should run automatically and patch everything within `patches`.

**Comment by bradleyflood** [comment] 2022-01-15 10:34
Thanks @sadikyalcin is this something you could create a pull request for to fix this in RNTP?

**Comment by jspizziri** [comment] 2022-04-13 14:31
This seems to be a duplicate of https://github.com/doublesymmetry/react-native-track-player/issues/1235#issuecomment-1098086394

I'm going to close it for now, but if I'm mistaken please let me know and I'll reopen it.

**Closed by jspizziri** 2022-04-13 14:31 UTC
Labels: Bug, Help Wanted, Android

**Comment by red-made** [comment] 2022-07-02 07:08
> > But I went a bit deeper and tried to make it work with latest [react-native-video](https://github.com/react-native-video/react-native-video) (as it's more often case with rn-track-player) which uses `exoplayer 2.13.2` as can be seen [here](https://github.com/react-native-video/react-native-video/blob/master/android-exoplayer/build.gradle#L31). So I created a patch file which can be used with [patch-package](https://github.com/ds300/patch-package).
> > Below is the content of the patch file and here is the link to the [gist](https://gist.github.com/kanzitelli/53aca11f6a5d701acf49d0de7c482253):
> > ```
> > diff --git a/node_modules/react-native-track-player/android/build.gradle b/node_modules/react-native-track-player/android/build.gradle
> > index a241d94..48138f9 100644
> > --- a/node_modules/react-native-track-player/android/build.gradle
> > +++ b/node_modules/react-native-track-player/android/build.gradle
> > @@ -60,7 +60,7 @@ dependencies {
> >      //noinspection GradleDynamicVersion
> >      implementation 'com.facebook.react:react-native:+'
> >      
> > -    def exoPlayerVersion = safeExtGet("exoPlayerVersion", '2.11.4')
> > +    def exoPlayerVersion = safeExtGet("exoPlayerVersion", '2.13.2')
> >  
> >      // ExoPlayer Core
> >      implementation "com.google.android.exoplayer:exoplayer-core:${exoPlayerVersion}"
> > diff --git a/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/MusicManager.java b/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/MusicManager.java
> > index 61d17bf..c9969b5 100644
> > --- a/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/MusicManager.java
> > +++ b/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/MusicManager.java
> > @@ -132,8 +132,8 @@ public class MusicManager implements OnAudioFocusChangeListener {
> >                  .setLoadControl(control)
> >                  .build();
> >  
> > -        player.setAudioAttributes(new com.google.android.exoplayer2.audio.AudioAttributes.Builder()
> > -                .setContentType(C.CONTENT_TYPE_MUSIC).setUsage(C.USAGE_MEDIA).build());
> > +        player.getAudioComponent().setAudioAttributes(new com.google.android.exoplayer2.audio.AudioAttributes.Builder()
> > +                .setContentType(C.CONTENT_TYPE_MUSIC).setUsage((C.USAGE_MEDIA)).build(), false);
> >  
> >          return new LocalPlayback(service, this, player, cacheMaxSize, autoUpdateMetadata);
> >      }
> > diff --git a/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/player/ExoPlayback.java b/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/player/ExoPlayback.java
> > index 37a6fbf..8e2d866 100644
> > --- a/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/player/ExoPlayback.java
> > +++ b/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/player/ExoPlayback.java
> > @@ -8,7 +8,7 @@ import com.facebook.react.bridge.Promise;
> >  import com.google.android.exoplayer2.*;
> >  import com.google.android.exoplayer2.Player.EventListener;
> >  import com.google.android.exoplayer2.Timeline.Window;
> > -import com.google.android.exoplayer2.extractor.mp4.MdtaMetadataEntry;
> > +import com.google.android.exoplayer2.metadata.mp4.MdtaMetadataEntry;
> >  import com.google.android.exoplayer2.metadata.Metadata;
> >  import com.google.android.exoplayer2.metadata.MetadataOutput;
> >  import com.google.android.exoplayer2.metadata.flac.VorbisComment;
> > @@ -247,7 +247,7 @@ public abstract class ExoPlayback<T extends Player> implements EventListener, Me
> >      public void onTimelineChanged(@NonNull Timeline timeline, int reason) {
> >          Log.d(Utils.LOG, "onTimelineChanged: " + reason);
> >  
> > -        if((reason == Player.TIMELINE_CHANGE_REASON_PREPARED || reason == Player.TIMELINE_CHANGE_REASON_DYNAMIC) && !timeline.isEmpty()) {
> > +        if((reason == Player.TIMELINE_CHANGE_REASON_PLAYLIST_CHANGED || reason == Player.TIMELINE_CHANGE_REASON_SOURCE_UPDATE) && !timeline.isEmpty()) {
> >              onPositionDiscontinuity(Player.DISCONTINUITY_REASON_INTERNAL);
> >          }
> >      }
> > diff --git a/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/player/SourceMetadata.java b/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/player/SourceMetadata.java
> > index 069cbbd..725feb9 100644
> > --- a/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/player/SourceMetadata.java
> > +++ b/node_modules/react-native-track-player/android/src/main/java/com/guichaguri/trackplayer/service/player/SourceMetadata.java
> > @@ -1,6 +1,6 @@
> >  package com.guichaguri.trackplayer.service.player;
> >  
> > -import com.google.android.exoplayer2.extractor.mp4.MdtaMetadataEntry;
> > +import com.google.android.exoplayer2.metadata.mp4.MdtaMetadataEntry;
> >  import com.google.android.exoplayer2.metadata.Metadata;
> >  import com.google.android.exoplayer2.metadata.flac.VorbisComment;
> >  import com.google.android.exoplayer2.metadata.icy.IcyHeaders;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @pybuche this might solve your problem as well :)
> > if it works well for you guys, I'll create a PR.
> 
> Thanks. I'll make it easier for peeps;
> 
> 1. Install `patch-package and postinstall` packages: `yarn add patch-package postinstall-postinstall`
> 2. Create `patches` directory on root and create `react-native-track-player+2.1.2.patch` inside `patches` directory with the above patch.
> 3. Add `"postinstall": "patch-package"` to the `scripts` block inside `package.json`
> 4. Run `yarn postinstall` and that should apply the patch(es);
> 
> ```
> patch-package 6.4.7
> Applying patches...
> react-native-track-player@2.1.2 ✔
> ```
> 
> Each time, you add a new package, the `postinstall` script should run automatically and patch everything within `patches`.

Tnx @[sadikyalcin](https://github.com/sadikyalcin) your code help me to avoid app crash, but when I do that:
```
        await TrackPlayer.add([track]);
        await TrackPlayer.play();    
``` 

nothing happen...
