### ISSUE TITLE
Cannot run on android with latest react native 0.65

### ISSUE THREAD

**Issue by xeoneux** [DoubleSymmetry/react-native-track-player#1239] opened 2021-08-20 14:06 UTC
**Describe the bug**
Cannot run on android with latest react native version

**To Reproduce**
Simply create a new project and add this library.

**Environment (please complete the following information):**
Run `react-native info` in your project and share the content.

```
❯ react-native info
info Fetching system and libraries information...
System:
    OS: macOS 11.5.2
    CPU: (8) arm64 Apple M1
    Memory: 104.36 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.7.0 - /opt/homebrew/bin/node
    Yarn: 1.22.11 - /opt/homebrew/bin/yarn
    npm: 7.21.0 - /opt/homebrew/bin/npm
    Watchman: 2021.08.02.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 29, 30
      Build Tools: 29.0.2, 30.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Arctic Fox 2020.3.1 Arctic Fox 2020.3.1
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_302 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.65.1 => 0.65.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

What `react-native-track-player` version are you using? 2.0.3
Are you testing on a real device or in the simulator? Which OS version are you running? Real

**Code**
Please, share the code that is causing the issue

```
$ react-native run-android --verbose
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 894 file(s) to forward-jetify. Using 8 workers...
info JS server already running.
info Installing the app...
> Task :app:checkDebugAarMetadata FAILED
5 actionable tasks: 2 executed, 3 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.google.android.exoplayer:exoplayer-core:2.11.4.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
       - file:/Users/xeoneux/.m2/repository/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
       - file:/Users/xeoneux/Projects/zy/zy/node_modules/react-native/android/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
       - file:/Users/xeoneux/Projects/zy/zy/node_modules/jsc-android/dist/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
       - https://dl.google.com/dl/android/maven2/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
       - https://www.jitpack.io/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
     Required by:
         project :app > project :react-native-track-player

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.google.android.exoplayer:exoplayer-core:2.11.4.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
       - file:/Users/xeoneux/.m2/repository/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
       - file:/Users/xeoneux/Projects/zy/zy/node_modules/react-native/android/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
       - file:/Users/xeoneux/Projects/zy/zy/node_modules/jsc-android/dist/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
       - https://dl.google.com/dl/android/maven2/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
       - https://www.jitpack.io/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
     Required by:
         project :app > project :react-native-track-player

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

    at makeError (/Users/xeoneux/Projects/zy/zy/node_modules/execa/index.js:174:9)
    at /Users/xeoneux/Projects/zy/zy/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/xeoneux/Projects/zy/zy/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:106:5)
    at async Command.handleAction (/opt/homebrew/lib/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:186:9)
```

**Comment by dcvz** [comment] 2021-08-20 16:06
Duplicate of #1235.

**Closed by dcvz** 2021-08-20 16:06 UTC
Labels: Bug, Needs Confirmation
