### ISSUE TITLE
[Android] lateinit property player has not been initialized

### ISSUE THREAD

**Issue by minhchienwikipedia** [doublesymmetry/react-native-track-player#1633] opened 2022-08-04 04:43 UTC
My users got issue `lateinit property player has not been initialized`, and Android only

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/20647079/182764611-2abc1e99-cbf4-4617-85ee-798ad7f4ec85.png">

This is my `setupPlayer` function
```javascript

export const setupTrackPlayer = async () => {
    try {
        if (global.isSetupTrackPlayer) {
            // this method will only reject if player has not been setup yet
            await TrackPlayer.getCurrentTrack();
        } else {
            await TrackPlayer.setupPlayer();
            await TrackPlayer.updateOptions({
                stopWithApp: true,
                capabilities: [
                    Capability.Play,
                    Capability.Pause,
                    Capability.SkipToNext,
                    Capability.SkipToPrevious,
                    Capability.Stop,
                ],
                compactCapabilities: [Capability.Play, Capability.Pause],
                progressUpdateEventInterval: 2,
            });
            global.isSetupTrackPlayer = true;
        }
    } catch {
        showToast({ message: 'Setup player fail!', type: 'fail' });
    }
};

```
And I put this function in useEffect of App.js file

Can you guys help me to fix this issue?!

**Comment by jspizziri** [comment] 2022-08-04 09:32
What version are you using? Please try to reproduce in the example app.

**Comment by jspizziri** [comment] 2022-08-07 10:36
Closing due to unresponsiveness.

**Comment by minhchienwikipedia** [comment] 2022-08-07 12:27
@jspizziri Sorry for replying late, I'm using version `2.2.0-rc3`

**Comment by jspizziri** [comment] 2022-08-07 13:54
@minhchienwikipedia Please upgrade to RC4 and retest

**Comment by anthonyeden** [comment] 2022-08-25 06:00
I encountered a similar bug on the nightly release.

When it crashes, I'm trying to empty the queue and add one new item.

From logcat:

`
08-25 15:58:48.950  3513  3513 E AndroidRuntime: java.lang.RuntimeException: Unable to stop service com.doublesymmetry.trackplayer.service.MusicService@345f195: kotlin.UninitializedPropertyAccessException: lateinit property player has not been initialized
08-25 15:58:48.950  3513  3513 E AndroidRuntime: 	at android.app.ActivityThread.handleStopService(ActivityThread.java:4689)
08-25 15:58:48.950  3513  3513 E AndroidRuntime: 	at android.app.ActivityThread.access$2100(ActivityThread.java:247)
08-25 15:58:48.950  3513  3513 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2096)
08-25 15:58:48.950  3513  3513 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-25 15:58:48.950  3513  3513 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
08-25 15:58:48.950  3513  3513 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
08-25 15:58:48.950  3513  3513 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7839)
08-25 15:58:48.950  3513  3513 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-25 15:58:48.950  3513  3513 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
08-25 15:58:48.950  3513  3513 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
08-25 15:58:48.950  3513  3513 E AndroidRuntime: Caused by: kotlin.UninitializedPropertyAccessException: lateinit property player has not been initialized
08-25 15:58:48.950  3513  3513 E AndroidRuntime: 	at com.doublesymmetry.trackplayer.service.MusicService.onDestroy(MusicService.kt:471)
08-25 15:58:48.950  3513  3513 E AndroidRuntime: 	at android.app.ActivityThread.handleStopService(ActivityThread.java:4669)
08-25 15:58:48.950  3513  3513 E AndroidRuntime: 	... 9 more
`

**Comment by anthonyeden** [comment] 2022-08-25 06:08
I think in my case, it's crashing when I do `await TrackPlayer.getCurrentTrack();` if there's nothing playing.

**Comment by minhchienwikipedia** [comment] 2022-08-25 09:07
Confirmed the version `2.2.0-rc4` fixed my issue. Maybe you can try it @anthonyeden

**Comment by jspizziri** [comment] 2022-08-31 16:35
@KrisLau can you reproduce this issue in the example app?

**Comment by KrisLau** [comment] 2022-08-31 16:40
@jspizziri Ok i'll try that out! I also created an issue #1693

**Comment by jspizziri** [comment] 2022-08-31 16:41
@KrisLau lets keep this on this issue. If you can reproduce it in the example app reliably I'll reopen this one and we can handle it right here.

**Comment by KrisLau** [comment] 2022-08-31 16:43
@jspizziri Ok i'll close that one then!

**Comment by KrisLau** [comment] 2022-08-31 17:48
@jspizziri Working on that repro but I just realized I forgot to include this part in the previous comment:
```

```

**Comment by KrisLau** [comment] 2022-08-31 17:49
@jspizziri Working on that repro but I just realized I forgot to include this part in the previous comment:
```
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.exoplayer2.Player$EventListener" on path: DexPathList[[zip file "/data/app/~~iW5DLLc0MbHqAWWG_Mjo7Q==/com.appname-WW3ZfkfrLQC1Yzh1sb60_A==/base.apk"],nativeLibraryDirectories=[/data/app/~~iW5DLLc0MbHqAWWG_Mjo7Q==/com.epicsports.epicmobile-WW3ZfkfrLQC1Yzh1sb60_A==/lib/x86, /data/app/~~iW5DLLc0MbHqAWWG_Mjo7Q==/com.epicsports.epicmobile-WW3ZfkfrLQC1Yzh1sb60_A==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at expo.modules.av.player.PlayerData.createUnloadedPlayerData(PlayerData.java:192) 
        at expo.modules.av.video.VideoView.setSource(VideoView.java:365) 
        at expo.modules.av.video.VideoView.setSource(VideoView.java:334) 
        at expo.modules.av.video.VideoViewManager.setSource(VideoViewManager.java:103) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at expo.modules.core.ViewManager.updateProp(ViewManager.java:90) 
        at expo.modules.adapters.react.views.ViewManagerAdapterUtils.setProxiedProperties(ViewManagerAdapterUtils.java:51) 
        at expo.modules.adapters.react.views.SimpleViewManagerAdapter.setProxiedProperties(SimpleViewManagerAdapter.java:49) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:93) 
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:136) 
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:56) 
        at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:48) 
        at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:144) 
        at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:77) 
        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:281) 
        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:194) 
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1110) 
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1081) 
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29) 
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175) 
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85) 
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970) 
        at android.view.Choreographer.doCallbacks(Choreographer.java:796) 
        at android.view.Choreographer.doFrame(Choreographer.java:727) 
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 

```

**Comment by jspizziri** [comment] 2022-08-31 17:49
@KrisLau it looks like you might be having an issue with multiple installations of ExoPlayer (expo-av + rntp). Please look at other issues for how people have worked around this.

**Comment by KrisLau** [comment] 2022-08-31 18:04
@jspizziri I tried looking around at some other issues like https://github.com/doublesymmetry/react-native-track-player/issues/1652 but their error cause is different I think from their error log printing `java.lang.IllegalStateException: Another SimpleCache instance uses the folder: /data/user/0/com.yc14ec100daa.www/cache/TrackPlayer` whereas mine is `java.lang.ClassNotFoundException: Didn't find class "com.google.android.exoplayer2.Player$EventListener"`. The first part of the error `java.lang.RuntimeException: Unable to stop service com.doublesymmetry.trackplayer.service.MusicService@c92725` is the same though so i might be wrong. 

Also not sure if this is relevant but I saw https://github.com/google/ExoPlayer/issues/4902 which I'm not sure if it is related at all.

**Comment by KrisLau** [comment] 2022-08-31 21:24
@jspizziri Managed to repro it with the same error at https://github.com/KrisLau/reproExoplayer. Error from Android Studio logcat:
```
2022-08-31 16:15:18.078 11671-11671/com.example D/AndroidRuntime: Shutting down VM
2022-08-31 16:15:18.079 11671-11671/com.example E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example, PID: 11671
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/Player$EventListener;
        at expo.modules.av.player.PlayerData.createUnloadedPlayerData(PlayerData.java:192)
        at expo.modules.av.AVManager.lambda$loadForSound$1$expo-modules-av-AVManager(AVManager.java:427)
        at expo.modules.av.AVManager$$ExternalSyntheticLambda1.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.exoplayer2.Player$EventListener" on path: DexPathList[[zip file "/data/app/~~C7lh4pNaUhs6vX4iUyfNdg==/com.example-t4y8AhcMP9xWIicEqkIjiw==/base.apk"],nativeLibraryDirectories=[/data/app/~~C7lh4pNaUhs6vX4iUyfNdg==/com.example-t4y8AhcMP9xWIicEqkIjiw==/lib/x86, /data/app/~~C7lh4pNaUhs6vX4iUyfNdg==/com.example-t4y8AhcMP9xWIicEqkIjiw==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at expo.modules.av.player.PlayerData.createUnloadedPlayerData(PlayerData.java:192) 
        at expo.modules.av.AVManager.lambda$loadForSound$1$expo-modules-av-AVManager(AVManager.java:427) 
        at expo.modules.av.AVManager$$ExternalSyntheticLambda1.run(Unknown Source:8) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

You just need to connect android studio to the emulator before clicking the "expo-av play" button. (it doesn't use the `playAsync` method, just the `createAsync`)

**Comment by stereodenis** [comment] 2022-09-01 07:15
Still facing this issue after exiting app (with no player initialization).

**Comment by KrisLau** [comment] 2022-09-01 18:08
@jspizziri so it looks like #1694 is the same issue and I just tested removing this package and just using `expo-av` works. The test for that is in the without-trackplayer branch of the same repo so I think it might have something to do with https://github.com/doublesymmetry/react-native-track-player/commit/c292dd80cfe93c4f2d7accdd601c5d7c275acc80 but I'm not sure exactly what

**Comment by KrisLau** [comment] 2022-09-01 20:51
@jspizziri Sorry I've tried a bunch of things but i don't think I'm any closer to figuring out what is causing it. I'm just not very good 
at this ahahaha and I'm not sure what else I should look into.

**Comment by rborn** [comment] 2022-09-02 10:08
I believe I found a fix, but my kotlin knowledge is -100 so maybe before making a PR someone could test? @KrisLau @jspizziri 

I changed the lines https://github.com/doublesymmetry/react-native-track-player/blob/6b25dfe2eaf8948b8613612cddf5ff6b8aa451ee/android/src/main/java/com/doublesymmetry/trackplayer/service/MusicService.kt#L472-L476

Where we need to check if plater actually is initialised being a `lateInit` variable to 
~~~
    @MainThread
    override fun onDestroy() {
        super.onDestroy()
        
        if (this::player.isInitialized ) {
               player.stop()
        }
     
    }
~~~

and  I suspect the `onTaskRemoved`  (line 456) also needs this, I added it just in case.

No more crashes for me, but please try and I'll make a PR if all goes well 🙏

**Comment by KrisLau** [comment] 2022-09-02 13:54
@rbor Just tested it on my local machine and it doesn't seem to work for me. This is the repo I used to test the change: https://github.com/KrisLau/reproExoplayer

**Comment by rborn** [comment] 2022-09-02 14:19
@KrisLau I edited the file directly in my node_modules, cleaned and compiled again. For me the crash was showing on app hot reload reload.

**Comment by puckey** [comment] 2022-09-02 14:20
@rborn Don't trust any crashes that happen on hot reload to also happen in production. Best to test a fresh run instead.

**Comment by rborn** [comment] 2022-09-02 14:21
@puckey my crashlytics is full of them 😅

**Comment by KrisLau** [comment] 2022-09-02 14:30
https://github.com/doublesymmetry/react-native-track-player/issues/1678 suggests that it might be a version mismatch for exoplayer but I'm not sure ahhaha

**Comment by KrisLau** [comment] 2022-09-02 15:36
@rborn For RNTP, i think someone else in the thread already mentioned that there are other solved issues for that

**Comment by rborn** [comment] 2022-09-02 15:37
@KrisLau do you have a link ? 🙏 ❤️

**Comment by KrisLau** [comment] 2022-09-02 15:46
I have no clue which issue they were referring to but a quick search of the issue pulls up this: https://github.com/doublesymmetry/react-native-track-player/issues/1679 which might be it

**Comment by KrisLau** [comment] 2022-09-02 16:22
If anyone who has any knowledge of using exoplayer a pull request to expo-av would be greatly appreciated. I tried upgrading it myself but I have no clue what I'm doing and I'm causing more errors hahaha. My issue in expo-av: https://github.com/expo/expo/issues/18937

**Comment by jspizziri** [comment] 2022-09-06 14:42
@mpivchev do we need to wrap access of `player` with `isInitialized` checks as is indicated here?

https://github.com/doublesymmetry/react-native-track-player/issues/1633#issuecomment-1235316807

**Comment by jspizziri** [comment] 2022-09-06 15:08
All, it looks like this was fixed via https://github.com/doublesymmetry/react-native-track-player/pull/1700. Please test via the nightly build, and let us know if the problem persists.

**Closed by jspizziri** 2022-09-06 15:08 UTC
Labels: Bug, Platform: Android, Needs Feedback

**Comment by KrisLau** [comment] 2022-09-14 16:51
For anyone interested, Expo maintainers are planning on upgrading the exoplayer version: 

- https://github.com/expo/expo/issues/18937#issuecomment-1246143690

**Comment by yanhongchang-1105** [comment] 2022-12-29 11:11
> @jspizziri Working on that repro but I just realized I forgot to include this part in the previous comment:
> 
> ```
> Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.exoplayer2.Player$EventListener" on path: DexPathList[[zip file "/data/app/~~iW5DLLc0MbHqAWWG_Mjo7Q==/com.appname-WW3ZfkfrLQC1Yzh1sb60_A==/base.apk"],nativeLibraryDirectories=[/data/app/~~iW5DLLc0MbHqAWWG_Mjo7Q==/com.epicsports.epicmobile-WW3ZfkfrLQC1Yzh1sb60_A==/lib/x86, /data/app/~~iW5DLLc0MbHqAWWG_Mjo7Q==/com.epicsports.epicmobile-WW3ZfkfrLQC1Yzh1sb60_A==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
>         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
>         at expo.modules.av.player.PlayerData.createUnloadedPlayerData(PlayerData.java:192) 
>         at expo.modules.av.video.VideoView.setSource(VideoView.java:365) 
>         at expo.modules.av.video.VideoView.setSource(VideoView.java:334) 
>         at expo.modules.av.video.VideoViewManager.setSource(VideoViewManager.java:103) 
>         at java.lang.reflect.Method.invoke(Native Method) 
>         at expo.modules.core.ViewManager.updateProp(ViewManager.java:90) 
>         at expo.modules.adapters.react.views.ViewManagerAdapterUtils.setProxiedProperties(ViewManagerAdapterUtils.java:51) 
>         at expo.modules.adapters.react.views.SimpleViewManagerAdapter.setProxiedProperties(SimpleViewManagerAdapter.java:49) 
>         at java.lang.reflect.Method.invoke(Native Method) 
>         at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:93) 
>         at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:136) 
>         at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:56) 
>         at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:48) 
>         at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:144) 
>         at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:77) 
>         at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:281) 
>         at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:194) 
>         at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1110) 
>         at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1081) 
>         at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29) 
>         at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175) 
>         at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85) 
>         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970) 
>         at android.view.Choreographer.doCallbacks(Choreographer.java:796) 
>         at android.view.Choreographer.doFrame(Choreographer.java:727) 
>         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957) 
>         at android.os.Handler.handleCallback(Handler.java:938) 
>         at android.os.Handler.dispatchMessage(Handler.java:99) 
>         at android.os.Looper.loop(Looper.java:223) 
>         at android.app.ActivityThread.main(ActivityThread.java:7656) 
>         at java.lang.reflect.Method.invoke(Native Method) 
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
> ```

Have you solved it now? Now I have met this problem and I am very anxious

**Comment by KrisLau** [comment] 2023-01-02 18:00
@yanhongchang-1105 Expo-AV has fixed this already on their end so if that's what's causing it for you upgrade your expo-av version. If it is something else you will have to check that library and open an issue there. React native track player cant do anything
