### ISSUE TITLE
App is crashing on IOS after deployment or in test-flight. Working fine locally. 

### ISSUE THREAD

**Issue by Raheel1258** [doublesymmetry/react-native-track-player#1477] opened 2022-04-16 16:38 UTC
**Describe the Bug**
The app is crashing on IOS after deployment on Appstore or Test flight. Working fine locally. 

**Steps To Reproduce**
Deploy the app on Appstore or create a test flight. Working fine on debug mode. Crashing on release mode for IOS.

**Code To Reproduce**
Here is the code when we load songs 

```
export const getMusicByTitle = (title, setAnimation) => dispatch => {
  setAnimation(true);
  axios
    .get(`${Api}/music/searchMusic?title=${title}`)
    .then(async res => {
      let arr = [];
      res?.data?.musics.forEach(x => {
        arr.push({
          id: x._id,
          url: x.audioUrl,
          title: x.title,
          artist: x.Artist,
          artwork: x.audioUrl,
        });
      });
      await TrackPlayer.destroy();
      await TrackPlayer.setupPlayer();
      await TrackPlayer.add(arr);
      dispatch(musicData(res?.data));
      setAnimation(false);
    })
    .catch(err => {
      setAnimation(false);
    });
};

```
**Environment Info:**

- Paste the results of `npx react-native info`
`Fetching system and libraries information...
(node:7414) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 12.3.1
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 23.26 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 23, 25, 28, 29, 30
      Build Tools: 30.0.2, 32.0.0
      System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_222 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found`
- Paste the exact `react-native-track-player` version you are using
    "react-native-track-player": "^2.1.2",

- Real device? Or simulator?
real Device

- What OS are you running?
IOS

**Comment by Raheel1258** [comment] 2022-04-16 16:39
Really need help to fix this guys.

**Comment by Raheel1258** [comment] 2022-04-16 16:40
Why the app is crashing when songs are loaded on IOS real device?

**Comment by jspizziri** [comment] 2022-04-16 18:59
At a glance my guess is that this has to do with your app and app environment rather than this lib, but I'll try and help.

I've used the lib in production before (and I'm sure others have too) and I've not experienced this.

Because it's in TestFlight we're really going to need a stacktrace or crash report to help you solve it.

**Comment by Raheel1258** [comment] 2022-04-17 09:52
I am loading the songs in the track player in this way the song URL is coming from s3. Is there any problem with this?  

`export const getMusicByTitle = (title, setAnimation) => dispatch => {
  setAnimation(true);
  axios
    .get(`${Api}/music/searchMusic?title=${title}`)
    .then(async res => {
      let arr = [];
      res?.data?.musics.forEach(x => {
        arr.push({
          id: x._id,
          url: x.audioUrl,
          title: x.title,
          artist: x.Artist,
          artwork: x.audioUrl,
        });
      });
      await TrackPlayer.destroy();
      await TrackPlayer.setupPlayer();
      await TrackPlayer.add(arr);
      dispatch(musicData(res?.data));
      setAnimation(false);
    })
    .catch(err => {
      setAnimation(false);
    });
};`

**Comment by jspizziri** [comment] 2022-04-17 11:32
Can you send the array of tracks? I'm guessing something is off there. Make sure they all have artists as there's a known bug on iOS where that field is actually required

**Comment by jspizziri** [comment] 2022-04-26 10:53
Closing this until feedback is provided. Sounds like a config issue.

**Closed by jspizziri** 2022-04-26 10:53 UTC
Labels: Bug, Platform: iOS, Needs Feedback

**Comment by Paovilla** [comment] 2022-09-22 19:22
I have the same issue, but in both Android and IOS .. the app is crashing on some Android and OIS devices (not all of them) after deployment. working fine locally. Here es the example of track, the three properties are string, the url propertie is something like this `https://${config.azureStorageAccount}.blob.core.windows.net/training-audios`.

  const track = {
    url: audioUri,
    title: 'title',
    artist: 'Mindtrackr',
  };

I really need help.

Thank you so much!

**Comment by jspizziri** [comment] 2022-09-22 19:25
@Paovilla what kind of file is located at the URL `https://${config.azureStorageAccount}.blob.core.windows.net/training-audios`? It's strange that it doesn't have a typically extension, perhaps try playing one of the audio files included in the example repository.

Make 100% sure that you're trying to play the same tracks locally as you are in testflight.

**Comment by Paovilla** [comment] 2022-09-22 19:36
In the repository there are .mp3 files and in the url  propertie of track I specify what audio to play, for example. 
  const trainingAudioBaseUrl = `https://${config.azureStorageAccount}.blob.core.windows.net/training-audios`;
  const trainingAudioUri = `${trainingAudioBaseUrl}/${trainingToShow.audio}`;
  const track = {
    url: trainingAudioUri,
    title: trainingToShow.title,
    artist: 'Mindtrackr',
  };

The issue happen in some devices not all, that is the reason that I know the track is ok, It could be something with the configuration?

**Comment by jspizziri** [comment] 2022-09-22 19:51
@Paovilla , I'm not sure I follow about the type of audio playback. But if you can create a reproduction based off of a fork of this repo (in the example project), I'll reopen.

Thanks!
