### ISSUE TITLE
Could not find com.google.android.exoplayer:exoplayer-core:2.11.4.

### ISSUE THREAD

**Issue by giorodri0584** [doublesymmetry/react-native-track-player#1235] opened 2021-08-19 23:37 UTC
**Describe the bug**
Hi I install react native track player on a fresh project
 and Im getting this error on android only:
Could not find com.google.android.exoplayer:exoplayer-core:2.11.4.
Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
       - https://dl.google.com/dl/android/maven2/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
       - https://www.jitpack.io/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom

**To Reproduce**
yarn add react-native-track-player

**Environment (please complete the following information):**
Run `react-native info` in your project and share the content.
System:
  Binaries:
    Node: 14.17.5 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.20.6 - /usr/local/bin/npm
    Watchman: 2021.08.02.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7583922
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.65.0 => 0.65.0
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
What `react-native-track-player` version are you using? 2.0.3
Are you testing on a real device or in the simulator?  android emulator
Which OS version are you running? MacOs Big Sur

**Code**
I get the error running the app

tried adding different maven url but none work.

**Comment by dcvz** [comment] 2021-08-20 07:39
Do you also get this issue when running the example?

**Comment by Tucker2015** [comment] 2021-08-20 08:45
Same issue here with fresh project.

**Comment by dcvz** [comment] 2021-08-20 10:54
I have just tried to make a new project and add the lib and it has worked.
These are the commands I used:

```bash
npx react-native init TestProject --template react-native-template-typescript
cd TestProject
yarn add react-native-track-player
yarn run android
```

**Comment by Tucker2015** [comment] 2021-08-20 11:57
> I have just tried to make a new project and add the lib and it has worked.
> These are the commands I used:
> 
> ```shell
> npx react-native init TestProject --template react-native-template-typescript
> cd TestProject
> yarn add react-native-track-player
> yarn run android
> ```

Thanks that worked ok.

**Comment by dcvz** [comment] 2021-08-20 12:07
@giorodri0584 I haven't heard from you yet. Can you try the above?

**Comment by giorodri0584** [comment] 2021-08-20 12:25
> @giorodri0584 I haven't heard from you yet. Can you try the abov

> @giorodri0584 I haven't heard from you yet. Can you try the above?

At work right now. I'll try it when I get a chance and let you know. Thanks for the quick response

**Comment by espenjanson** [comment] 2021-08-20 18:13
@dcvz next os, next issue! Same here, not working for me with react-native 0.65 and android. Exactly the same error message when I try to run  ./gradlew bundleRelease

**Comment by espenjanson** [comment] 2021-08-20 18:15
FYI, npx npx react-native init TestProject --template react-native-template-typescript does not create a react-native project with 0.65.1 but rather 0.64.2(?) (I found this out bugfixing my ios issue)

**Comment by dcvz** [comment] 2021-08-20 18:20
@espenjanson does it work when you follow the commands in my comment above? My guess is your project is not including one of the important repositories. Like maven central.

Although perhaps it's the other way around.. I'll take a look more carefully now that you point out that the commands I used don't generate a 0.65 project.

How are you creating a new project?

**Comment by dcvz** [comment] 2021-08-20 18:27
@espenjanson can you post the contents of your gradle file in your Android project?

**Comment by espenjanson** [comment] 2021-08-20 18:28
Sure!

`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "29.0.3"
        minSdkVersion = 25
        compileSdkVersion = 29
        targetSdkVersion = 29
        ndkVersion = "21.4.7075529"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:4.1.0")
        classpath('com.google.gms:google-services:4.3.3')
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
    }
}
`

**Comment by dcvz** [comment] 2021-08-20 18:34
@espenjanson if you try the command I mentioned above (which does not use 0.65) does it run for you?

There must be some difference in the gradle files across versions. I'm not at my computer atm though to check.

**Comment by xeoneux** [comment] 2021-08-20 18:34
In the latest changelog at https://github.com/facebook/react-native/releases/tag/v0.65.0, it mentions: JCenter has been sunsetted and read-only now. We have removed JCenter as a maven repository and updated dependencies to use MavenCentral and Jitpack.

Is that the reason?

**Comment by dcvz** [comment] 2021-08-20 18:40
@xeoneux this definitely would be the reason.. I thought that might be it but the gradle file @espenjanson posted still has jcenter() in it.

So I was a bit confused. But if jcenter is no longer in the gradle file then that would be the reason.

I'll have to update the dependency to a version that's published to maven central.

**Comment by espenjanson** [comment] 2021-08-20 18:44
Haha, sorry @dcvz my bad there, I actually just included jcenter() - however, it's still not building for me. Not sure if it's because of track-player though since there seems to be plenty of libraries hit hard by 0.65, I'm currently stuck because of react-native-reanimated (it seems).

**Comment by dcvz** [comment] 2021-08-20 19:41
Ok, I have updated the example in the repo to RN 0.65.0 and can confirm the issue.

For now the workaround is to add `jcenter()` to `allprojects { repositories { ` like I've done here: https://github.com/DoubleSymmetry/react-native-track-player/commit/5b3084745a58f81c1e49a5737e300801dc714cd7

The better fix will be to update the exoplanet dependency to one that is released under maven central but that will require some more work. I'll keep this issue open until then.

**Comment by giorodri0584** [comment] 2021-08-21 00:27
> Ok, I have updated the example in the repo to `RN 0.65.1` and can confirm the issue.
> 
> For now the workaround is to add `jcenter()` to `allprojects { repositories { ` like I've done here: [5b30847](https://github.com/DoubleSymmetry/react-native-track-player/commit/5b3084745a58f81c1e49a5737e300801dc714cd7)
> 
> The better fix will be to update exoplayer to a version that is released under maven central but that will require some more work. I'll keep this issue open until then.

Thanks a lot. It is working now.

**Comment by neoassyrian** [comment] 2021-09-11 17:07
@dcvz I can confirm having the same issue and adding jcenter fixes the issue. Also running RN 0.65.1.

**Comment by dcvz** [comment] 2021-09-16 21:29
Didn't realise this got closed. Reopening until it's fully fixed and not just worked around.

**Comment by GrimDev** [comment] 2021-09-20 14:29
@dcvz Do you know that we are not able to compile our app anymore while this is not fixed ?
It is a critical issue. Is there any workaround (calling jcenter() won't work anymore), or quick fix ?

**Comment by dcvz** [comment] 2021-09-20 19:45
@GrimDev we know its an important issue and we're working on a fix. At the moment using `jcenter()` is still a valid workaround.. You cannot publish new packages there but it is still available as read-only.

**Comment by espenjanson** [comment] 2021-09-20 20:17
@GrimDev As far as I know there's nothing wrong with doing this (yet?)

` repositories {

        mavenLocal()
        mavenCentral()
        jcenter()
        google()

}`

**Comment by GrimDev** [comment] 2021-09-21 07:56
I guess jcenter was down when I tried last time, it seems to work today, sorry for then warn

**Comment by SNNikitin** [comment] 2021-09-24 13:47
Any updates?
Have same issue...

**Comment by GoodNews-Myanmar-Developer** [comment] 2021-09-26 08:22
> @espenjanson can you post the contents of your gradle file in your Android project?



> Ok, I have updated the example in the repo to `RN 0.65.1` and can confirm the issue.
> 
> For now the workaround is to add `jcenter()` to `allprojects { repositories { ` like I've done here: [5b30847](https://github.com/DoubleSymmetry/react-native-track-player/commit/5b3084745a58f81c1e49a5737e300801dc714cd7)
> 
> The better fix will be to update exoplayer to a version that is released under maven central but that will require some more work. I'll keep this issue open until then.

Thanks a lot sir. I stuck with this several day :) 💯

**Comment by SNNikitin** [comment] 2021-09-27 08:11
Have you any plans to move to maven or something else to avoid the jcenter-related riscs?

**Comment by dcvz** [comment] 2021-09-27 08:12
@SNNikitin please take the time to look through the thread. This question has been answered. We're working on it.

**Comment by SNNikitin** [comment] 2021-09-27 08:14
Thanks for your answer! :)
I'm just slightly frustrated, please sorry!

**Comment by bBSempai** [comment] 2021-10-31 13:18
> Ok, I have updated the example in the repo to `RN 0.65.1` and can confirm the issue.
> 
> For now the workaround is to add `jcenter()` to `allprojects { repositories { ` like I've done here: [5b30847](https://github.com/DoubleSymmetry/react-native-track-player/commit/5b3084745a58f81c1e49a5737e300801dc714cd7)
> 
> The better fix will be to update exoplayer to a version that is released under maven central but that will require some more work. I'll keep this issue open until then.

Well I did this added jcenter() to my build.gradle and tried this on a fresh project but I am still getting the same error can anyone please help as soon as I install react-native-track-player my application fails to build.
It would mean a lot thank you.

```
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 899 file(s) to forward-jetify. Using 8 workers...
info Starting JS server...
info Installing the app...
> Task :app:checkDebugAarMetadata FAILED
5 actionable tasks: 2 executed, 3 up-to-date
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01  
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01      
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.google.android.exoplayer:exoplayer-core:2.11.4.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
       - file:/C:/Users/bbwha/.m2/repository/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
       - file:/C:/Users/bbwha/Downloads/Documents/project/node_modules/react-native/android/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
       - file:/C:/Users/bbwha/Downloads/Documents/project/node_modules/jsc-android/dist/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
       - https://dl.google.com/dl/android/maven2/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
       - https://www.jitpack.io/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
     Required by:
         project :app > project :react-native-track-player

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.google.android.exoplayer:exoplayer-core:2.11.4.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
       - file:/C:/Users/bbwha/.m2/repository/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
       - file:/C:/Users/bbwha/Downloads/Documents/project/node_modules/react-native/android/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
       - file:/C:/Users/bbwha/Downloads/Documents/project/node_modules/jsc-android/dist/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
       - https://dl.google.com/dl/android/maven2/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
       - https://www.jitpack.io/com/google/android/exoplayer/exoplayer-core/2.11.4/exoplayer-core-2.11.4.pom
     Required by:
         project :app > project :react-native-track-player

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s

    at makeError (C:\Users\bbwha\Downloads\Documents\project\node_modules\execa\index.js:174:9)
    at C:\Users\bbwha\Downloads\Documents\project\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async runOnAllDevices (C:\Users\bbwha\Downloads\Documents\project\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:106:5)
    at async Command.handleAction (C:\Users\bbwha\Downloads\Documents\project\node_modules\@react-native-community\cli\build\index.js:192:9)
info Run CLI with --verbose flag for more details.
```

Build.gradle: 
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
        ndkVersion = "21.4.7075529"
    }
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:4.2.2")
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenCentral()
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        maven { url 'https://www.jitpack.io' }
    }
}

```

**Comment by Tucker2015** [comment] 2021-10-31 15:00
Add jcenter() to allprojects section too

**Comment by bBSempai** [comment] 2021-10-31 20:45
> Add jcenter() to allprojects section too

thank you that worked!

**Comment by AkshayWazir** [comment] 2021-11-20 12:19
It still gives different error after doing this.

**Comment by mrigo** [comment] 2021-11-20 12:42
This isn't working with the newer version of react native and android requirements.
jcenter() will create conflicts with mavenCentral repository.
we can't use a greater version of exoplayer because the library is outdated and too big to be fixed with a patch.
There are a lot of classes not more available in exoplayer newer versions :(
Are you going to update the lib?
Because I have a lot of apps in productions that are using this library and no one of these now is working :(

**Comment by Ibrahimkhanlimurad** [comment] 2021-11-22 14:34
As jCenter was removed from react-native v0.65+ and no longer allows package updates, all packages should be obtained from mavenCentral. Thus, I would recommend defining the package such that other dependencies are no longer fetched from jCenter. So it is better to include jCenter dependent modules/groups to `android/build.gradle` like this:

```
allprojects {
    repositories {
        ...
        jcenter() {
            content {
                includeGroup("com.google.android.exoplayer")
            }
        }
        ...

    }
}
```

**Comment by fatlinesofcode** [comment] 2021-12-01 22:10
same issue on react-native 0.66

**Comment by vladimirevstratov** [comment] 2021-12-29 22:26
> As jCenter was removed from react-native v0.65+ and no longer allows package updates, all packages should be obtained from mavenCentral. Thus, I would recommend defining the package such that other dependencies are no longer fetched from jCenter. So it is better to include jCenter dependent modules/groups to `android/build.gradle` like this:
> 
> ```
> allprojects {
>     repositories {
>         ...
>         jcenter() {
>             content {
>                 includeGroup("com.google.android.exoplayer")
>             }
>         }
>         ...
> 
>     }
> }
> ```

Thank you vary much!

**Comment by lelukas** [comment] 2022-02-22 19:22
Guys, shouldn't this be described on lib's documentation website?

**Comment by Pustaka-Digital-Media** [comment] 2022-03-22 16:30
Is there still any stable/fully working fix to this, I'm about to release an app with this library and I cannot generate an APK to test it, can someone please help.

**Comment by ShivamJoker** [comment] 2022-03-30 07:48
Faced the same issue, at least doc should say in troubleshooting we need to add jccenter manually

**Comment by jspizziri** [comment] 2022-04-13 13:59
All,

I understand that this is a super frustrating issue to encounter when trying to get new installs or upgrades running. With that said, `v2.2.0` (currently in rc with [`v2.2.0-rc3`](https://github.com/doublesymmetry/react-native-track-player/releases/tag/v2.2.0-rc3) fixes this issue. As all the team efforts are going into that release we're not going to address this issue for `v2.1.0`.

I know it stinks! But it's the reality of the situation. The good news is that there is ample information on this issue to help folks find the solution for this issue themselves.

The issue will remain open until v2.2.0 is out of RC at which time it will be closed.

**Comment by WAQAZ0178** [comment] 2022-05-10 09:33
> As jCenter was removed from react-native v0.65+ and no longer allows package updates, all packages should be obtained from mavenCentral. Thus, I would recommend defining the package such that other dependencies are no longer fetched from jCenter. So it is better to include jCenter dependent modules/groups to `android/build.gradle` like this:
> 
> ```
> allprojects {
>     repositories {
>         ...
>         jcenter() {
>             content {
>                 includeGroup("com.google.android.exoplayer")
>             }
>         }
>         ...
> 
>     }
> }
> ```

this one help me thank u buddy

**Comment by stereodenis** [comment] 2022-08-09 06:47
This is not stale. It still conflicts with react-native-track-player's exoplayer (from KotlinAudio)

**Comment by jspizziri** [comment] 2022-08-30 18:53
`v3.1` is now out and fixes this issue. Please upgrade to the latest version.

**Closed by jspizziri** 2022-08-30 18:53 UTC
Labels: Bug, Platform: Android, android-rewrite
