### ISSUE TITLE
iOS: operations do not guarantee order of execution in async JS functions

### ISSUE THREAD

**Issue by vjeranc** [doublesymmetry/react-native-track-player#1117] opened 2021-02-12 13:52 UTC
I've noticed that some sequence of calls will not work.
```javascript
await TrackPlayer.reset();
await TrackPlayer.add(track);
```

The code above will sometimes clear the added track. The reset happens after the track is added to the queue.

Also if I track the player position:
```javascript
await TrackPlayer.getPosition();
await TrackPlayer.getCurrentTrack();
await TrackPlayer.getDuration();
```
I'll sometimes get the state that current track switched to the next one but the position and the duration are from the previous track.

From looking at the code it looks like `reject` `resolve` functions in the RN bridge are instantly resolved in some cases. Swift does not seem to use them when async code is run.
Android on the other hand wraps the promise into runnable and I guess resolves it correctly.

Also, if some of these state values will update inbetween `await` calls maybe a unified call for the whole player state is a better interface.

**Comment by marcinkieruzel** [comment] 2021-02-17 12:53
Sounds like me case as well

**Comment by vjeranc** [comment] 2021-02-17 14:44
To clarify,
```
await TrackPlayer.reset();
await TrackPlayer.add(track);
```
If player is playing and `reset` is called on track end, then if another track is added the position and duration lags and the player (on native side) thinks that it's the new track that is also ending, so it clears it too.

There seems to be a lot of issues with internal state.

**Comment by TheFrostage** [comment] 2021-05-05 10:17
According to logs in XCode, the reset function triggers multiple times. Here is the code:

```
await TrackPlayer.reset();
await TrackPlayer.add(queue);
await TrackPlayer.skip(track.id);
```

![Screen Shot 2021-05-05 at 13 14 18](https://user-images.githubusercontent.com/46031765/117126695-cf0de180-ada3-11eb-9300-558a7d46146d.png)

Is there a workaround to reset playback, clear the queue, fill it with new tracks & skip to a specific track?

**Comment by fivecar** [comment] 2023-03-18 02:28
@dcvz : is this actually fixed? I ask because I continue to get these issues -- particularly what @vjeranc raised, where you get multiple tracks prematurely ended because a track added after reset is sometimes mistakenly PlaybackQueueEnded.

You can also get inconsistencies in these two other conditions:
```typescript
await TrackPlayer.reset();
const queue = await TrackPlayer.getQueue();
// queue.length > 0 (!)
```
and
```typescript
await TrackPlayer.add(track);  // where track.duration > 0
const duration = await TrackPlayer.getDuration();
// duration === 0 (!)
```

These issues happen frequently enough (e.g. the OP's issue happens to me all the time; scenario 1 above happens sometimes, and scenario 2 seems to consistently happen, all on iOS) to pose some real issues for the app I'm building.

If this fixed, could you explain what the fix was? If it's not fixed, is there a workaround?

**Comment by fivecar** [comment] 2023-03-18 04:50
Ok - I've found the issue for the last example (TrackPlayer.add() followed by inexplicable zero duration). Here's the sequence:

1. `add()` in trackPlayer.ts calls into `player.add` on the native side (RNTrackPlayer.swift). It resolves the promise to whatever index you asked it to add at _without the track actually being fully added_. So on the JS side, you move on from your `await` without knowing it's not fully done. Everything after this step happens in SwiftAudioEx.
2. `player.add` eventually triggers AVPlayerWrapper.swift's `load()` (via `onCurrentItemChanged` in `QueuedAudioPlayer`) to process the added track. The key is that `load()` processes things asynchronously (using `AVURLAsset.loadValuesAsynchronously`). This all happens after the original TrackPlayer promise has already resolved from your `add()` call.
3. When `load()` finally gets things processed, it adds the newly loaded track, setting `self.item` as well as calling `avPlayer.replaceCurrentItem()` so the OS itself actually recognizes a new track. It's only at this point, after setting `avPlayer.currentItem`, that any `TrackPlayer.getDuration()` calls will actually return the right duration.

The net of it is that `TrackPlayer.add()` will resolve before it's really ready for subsequent calls (e.g. any other `TrackPlayer` call that depends on `avPlayer.currentItem` will give the wrong information). There's no notification mechanism out of SwiftAudioEx for you to await on in order to be sure things are truly loaded.

Because this causes all sorts of problems, `AVPlayerWrapper` has `timeToSeekToAfterLoading` and `playWhenReady` — two variables that try to absorb the impact of you calling `play()` and `seek()` after `TrackPlayer.add()` without knowing that the track isn't even really loaded yet. But `getDuration()` is something that can be delay-executed, since it depends on `AVPlayer`'s take on the duration.

A full solution to this isn't clear to me yet. It's not as easy as just blocking on promise resolution until `AVPlayerWrapper.load()` finishes its async work, because the mechanism by which `load()` is called isn't even directly chained from `RNTrackPlayer.add()`, since `load()` is ultimately triggered by `QueueManagerDelegate.onCurrentItemChanged()` noticing that the queue has a new top item in it.

Perhaps `TrackPlayer` can support an `addSynchronous()` that doesn't depend on `QueueManagerDelegate` noticing changes, but instead calls `AVPlayerWrapper.load()` and passes it a callback that resolves the promise when the track is truly loaded. You wouldn't want to necessarily make the default `add()` do this, since adding tracks _other than the first one_ shouldn't pose any of these sorts of problems.

The really painful part is that there aren't other things you can call on `TrackPlayer` to even know that it's fully added the item you asked for. I suppose you could poll on `getDuration` until it finally returns the value you passed it in `add()`; you can't just poll until it's nonzero, since SwiftAudioEx technically will simply give you the previous top track's duration.

**Comment by vjeranc** [comment] 2023-03-18 19:38
There were some fixes here https://github.com/inkitt/react-native-track-player/ , that somewhat stabilized the player.

**Comment by fivecar** [comment] 2023-03-18 22:02
@vjeranc : Forks are so hard to decide to take (e.g. what's the commitment of the inkitt folks to keeping up to date with changes from this repo?). What are some of the key changes that inkitt makes?

I've since discovered that even `add()` followed by `remove(0)` won't update the current native track (because of a bug in `QueueManager.mutateCurrentIndex` which assumes that if the index of the current item hasn't changed, AVPlayer's `item` doesn't need to either).

I've been going down that rabbit hole to try to make a PR to this repo, but would rather not continue patching if inkitt has moved beyond these issues.

**Comment by vjeranc** [comment] 2023-03-18 22:48
@fivecar I am no longer at Inkitt.

Key changes include making sure `resolve/reject` handles passed through RNBridge are called at the right moment. This stabilized the JS ops that were required by the app. One example, `seek` is an async op and was not treated as such.

From what I remember, going through the code, Android bits were nice and working well.
iOS bits are for some reason quite complicated, with delegates, a lot of state etc. I have no idea if it's the [Apple Media Player](https://developer.apple.com/documentation/mediaplayer) that is hard to use, or if incorrect usage resulted in a variety of patchwork in iOS bits that obscured the core issue.

The linked repo does not fix all of the issues. Magically, JS+Native bits work correctly for the required usage (which was auto switch track on end -- queuing was not used).

The best use of your time might be to look into Apple Media Player lib and do the RN bridge on iOS yourself.

**Comment by vjeranc** [comment] 2023-03-18 22:51
@fivecar sorry, I meant [AVPlayer](https://developer.apple.com/documentation/avfoundation/avplayer)!

**Comment by fivecar** [comment] 2023-03-19 00:15
Just submitted #1965 to patch `reset()` and `add()` in the meantime. That PR fixes all three race conditions noted in this bug, but does not fix `remove()` and a slew of soon-to-come features from SwiftAudioEx (e.g. `moveItem`, `replaceItem`), all of which will have this issue.

@vjeranc : I'd seriously consider wrapping AVPlayer, but I've already invested quite a bit in this current repo (e.g. fixing `updateOptions`, `reset` (in another scenario), and the constant loss of `playRate`). It makes me tired to think of reproducing all that (and carefully not regressing those things); and I'd ultimately prefer to make this project more successful if the maintainers make it possible, since other people will still hit all these issues (and likely haven't invested the type of time I have in trying to find the causes).

@puckey : LMK what you think of this patch in the meantime. I've tried to minimize the impact of the polling to restrict it only to the cases where we're sure SwiftAudioEx isn't going to handle things correctly (i.e. when the current track is affected).

**Comment by puckey** [comment] 2023-03-21 16:07
Spent the day working on a pr to implement async await in SwiftAudioEx: https://github.com/doublesymmetry/SwiftAudioEx/pull/44

The RNTP side is still left to be done..

**Comment by puckey** [comment] 2023-03-21 21:00
(I chose to close the async await pr again, as I don't see how it actually improves anything..)

**Comment by puckey** [comment] 2023-03-31 10:42
Closing for now because part of this issue has been [fixed](https://github.com/doublesymmetry/SwiftAudioEx/commit/b10aea494fd7de7dc0bd95cc229deb92ed335591), part of the issue is by design (we don't wait for load to reach the phase where a duration is already available) and part of the issue can not be reproduced (non zero, non correct duration after calling `add`)

**Closed by puckey** 2023-03-31 10:42 UTC
Labels: Bug

**Comment by fivecar** [comment] 2023-03-31 17:41
@puckey : Apologies for late reply, but I've been traveling a lot and away from the computer.

I still get a repro, even with today's codebase. For clarity, here is my whole QueueInitialTrackService.ts, in example/:
```typescript
import TrackPlayer, { Track } from 'react-native-track-player';

import playlistData from '../assets/data/playlist.json';
// @ts-expect-error – sure we can import this
import localTrack from '../assets/resources/pure.m4a';
// @ts-expect-error – sure we can import this
import localArtwork from '../assets/resources/artwork.jpg';

export const QueueInitialTracksService = async (): Promise<void> => {
  await TrackPlayer.add([
    ...(playlistData as Track[]),
    {
      url: localTrack,
      title: 'Pure (Demo)',
      artist: 'David Chavez',
      artwork: localArtwork,
      duration: 28,
    },
  ]);
  const [dur, prog, queue] = await Promise.all([
    TrackPlayer.getDuration(),
    TrackPlayer.getProgress(),
    TrackPlayer.getQueue(),
  ]);

  console.log(
    '* * * QueueInitialTracksService dur',
    dur,
    'prog',
    prog,
    'queueCount',
    queue.length
  );

  await TrackPlayer.remove(0);
  const newDur = await TrackPlayer.getDuration();
  console.log('* * * QueueInitialTracksService newDur', newDur);
};
````

With this, in today's build off `main` on the iOS simulator, I get the following output:
```console
 BUNDLE  ./index.js 

 LOG  Running "example" with {"rootTag":1,"initialProps":{}}
 LOG  getInitialURL null
 LOG  Event.PlaybackState {"state": "loading"}
 LOG  Event.PlaybackActiveTrackChanged {"index": 0, "lastPosition": 0, "track": {"artist": "David Chavez", "artwork": "https://react-native-track-player.js.org/example/Longing.jpeg", "duration": 143, "title": "Longing", "url": "https://react-native-track-player.js.org/example/Longing.mp3"}}
 LOG  * * * QueueInitialTracksService dur 0 prog {"buffered": 0, "duration": 0, "position": 0} queueCount 7
 WARN  Could not find image file:///Users/philipsu/Library/Developer/CoreSimulator/Devices/E955DBC6-8F52-4289-84A6-7C4C85BF0932/data/Containers/Bundle/Application/E5BBAF76-BC8B-4079-9016-10AA333EA7D7/example.app/undefined.png
 LOG  Event.PlaybackState {"state": "paused"}
 LOG  Event.PlaybackState {"state": "loading"}
 LOG  Event.PlaybackActiveTrackChanged {"index": 0, "lastIndex": 0, "lastPosition": 0, "lastTrack": {"artist": "David Chavez", "artwork": "https://react-native-track-player.js.org/example/Longing.jpeg", "duration": 143, "title": "Longing", "url": "https://react-native-track-player.js.org/example/Longing.mp3"}, "track": {"artist": "David Chavez", "artwork": "https://react-native-track-player.js.org/example/Soul%20Searching.jpeg", "duration": 77, "title": "Soul Searching (Demo)", "url": "https://react-native-track-player.js.org/example/Soul%20Searching.mp3"}}
 LOG  * * * QueueInitialTracksService newDur 0
```
As you can see, the duration reports as zero right after calling`add()`. This repros consistently for me... and from reading the code, it's fully explained (but IMO unexpected) behavior.

If it's by design that `getDuration()` can give you a different result from the duration of the track you just added, how is a user of the library supposed to deal with this (since there aren't notifications to the JS side on when a track is fully loaded, IIUC)?
