### ISSUE TITLE
TrackPlayerEvents Does not exist!

### ISSUE THREAD

**Issue by koushal141** [DoubleSymmetry/react-native-track-player#1231] opened 2021-08-15 08:29 UTC
In the latest version, "^2.0.1" TrackPlayerEvents dows not exist

**Comment by hiroyaiizuka** [comment] 2021-08-16 07:22
+1

I was using v1.2.7.
This is the image when to start music in which nextTruck is dummyId.
![1BD89F60-CE77-4E0A-A1FE-CC48AA763C00](https://user-images.githubusercontent.com/39001773/129525799-d5914c9e-48af-49cd-b6e5-bddba25e565e.png)


This is the image of v2.0.1 when to start music.

![461DD7B8-4151-41F3-9CC8-18C2300A6370](https://user-images.githubusercontent.com/39001773/129526062-01847c6a-ef9c-4fdb-ad2d-ad7b743a3228.png)

As shown above, nextTruck always becomes 0.

**Comment by ebrahimmelngary** [comment] 2021-08-18 00:42
i also faced this issue when upgrading to 2.0.2 from v 1.2.7

![Screen Shot 2021-08-18 at 2 34 42 AM](https://user-images.githubusercontent.com/26544537/129818538-95ec778b-0f96-4f13-bf13-3b9c6630e103.png)

**Comment by arabold** [comment] 2021-08-18 15:56
A lot of the default types have changed in the 2.0.0 update. Instead of `TrackPlayerEvents` use `Event`. I.e. `Event.PlaybackState` instead of `TrackPlayerEvents.PLAYBACK_STATE`. There's also `State` which replaces `TrackPlayer.STATE_*`.

Once you have updated your code accordingly, things will start to work. At least for me, they did. I also highly, highly recommend TypeScript which points out these errors immediately before even running the code.

**Comment by dcvz** [comment] 2021-08-19 07:39
Thank you all for providing answers!

@koushal141 I've better documented some of the breaking changes going into v2 in the README. Please use that to guide your migration :)

**Comment by dcvz** [comment] 2021-08-19 07:40
I will close this now as its not a bug, I hope the README provides all the information needed now.

**Closed by dcvz** 2021-08-19 07:40 UTC
Labels: Bug, Needs Confirmation
