### ISSUE TITLE
Crash on Android

### ISSUE THREAD

**Issue by mohity777** [doublesymmetry/react-native-track-player#1193] opened 2021-06-20 18:58 UTC
**Describe the bug**
My android app is crashing but it is working fine on IOS. it crashes 1 time in every 3 -4 attempts not every time -

Exception in native call-
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.post(java.lang.Runnable)' on a null object reference

Image ->> https://lh3.googleusercontent.com/-xaRP4BB5EHk/YM-PoYdmWLI/AAAAAAAABvg/t0LIUg2bcsEl8KC4IfRjNqIkBY077OjAQCJEEGAsYHg/s0/2021-06-20.jpg?authuser=0

**To Reproduce**

**Environment (please complete the following information):**
Run `react-native info` in your project and share the content.

System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz
    Memory: 490.54 MB / 7.78 GB
  Binaries:
    Node: 12.18.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.1, 30.0.2
      System Images: android-22 | Intel x86 Atom_64, android-28 | Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: 22.1.7171670
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7322048
    Visual Studio: Not Found
  Languages:
    Java: 1.8.0_211
    Python: 3.8.3
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

What `react-native-track-player` version are you using?
    "react-native-track-player": "^1.2.7",

Are you testing on a real device or in the simulator? Which OS version are you running?

On real device

**Code**
Please, share the code that is causing the issue

```
const setupPlayer = async () => {
    await TrackPlayer.setupPlayer();
    await TrackPlayer.updateOptions({
        stopWithApp: true,
        capabilities: [
            TrackPlayer.CAPABILITY_PLAY,
            TrackPlayer.CAPABILITY_PAUSE,
            TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
            TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
            TrackPlayer.CAPABILITY_STOP,
        ],
        compactCapabilities: [
            TrackPlayer.CAPABILITY_PLAY,
            TrackPlayer.CAPABILITY_PAUSE,
        ],
        notificationCapabilities: [
            TrackPlayer.CAPABILITY_PLAY,
            TrackPlayer.CAPABILITY_PAUSE,
            TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
            TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
            TrackPlayer.CAPABILITY_STOP,
        ],
    });
};

//***** For Generating playlist of audios

export const generatePlaylistFromTimeline = (startIndex) => {
    return async (dispatch, getState) => {
        await setupPlayer();
        const timelineState = getState().timeline.timeline;
        let newsList = [...timelineState.feed];
        const startIndexId = newsList[startIndex] ? newsList[startIndex].id : 0 ;
        console.log("!!!!",startIndexId);
        newsList = newsList.filter(item => item.type === 'news');
        newsList = newsList.map(item => item.id);

        const userState = getState().user;
        const newsInterests = userState.newsInterests || [];
        const identifier = newsInterests.join(',');

        let lastId = newsList[newsList.length - 1];
        let lastTime = getState().news.byIds[lastId].createdAt;
        console.log('Generating LastTime: ', lastTime);
        lastTime = new Date(lastTime).getTime();
        console.log('Generating LastTime: ', lastTime);
        console.log(newsList);
        const newStartIndex = newsList.indexOf(startIndexId);
        console.log(newStartIndex);
        const payload = {
            tracks: newsList,
            currentTrack: newsList[newStartIndex],
            identifier: identifier,
            lastTime: lastTime,
            paging: timelineState.paging,
        };
        dispatch(savePlaylist(payload));
        await setTracks(newsList, newStartIndex, getState);
    };
};

// *** Start playing the selected track

const setTracks = async (trackList, startIndex, getState) => {
    const newsByIds = getState().news.byIds;
    await TrackPlayer.reset();
    const tracks = trackList.map(track => {
        const newsItem = newsByIds[track];
        return {
            id: track,
            url: newsItem.audioUrl,
            title: newsItem.headline,
            artist: newsItem.categories[0],
            artwork: newsItem.images[0],
        };
    });
    await TrackPlayer.add(tracks);
    await TrackPlayer.skip(trackList[startIndex]);
    await TrackPlayer.play();
};
```

**Comment by mohity777** [comment] 2021-06-20 19:58
EDIT - It is occuring if player.destroy() throws some error  
Receiver not registered: com.guichaguri.trackplayer.service.MusicManager

**Comment by ebrahimmelngary** [comment] 2021-08-31 16:11
You should to get  capabilities from Capability not from TrackPlayer
   example:-
   
   capabilities: [
          Capability.Play,
          Capability.Pause,
          Capability.Stop,
          Capability.JumpForward,
          Capability.JumpBackward,
        ],

**Comment by mohity777** [comment] 2021-08-31 17:03
The code i have written is for V1.2.3, The one you have written down is for the new version V2.0.0

**Comment by mitchdowney** [comment] 2021-11-02 00:26
The "attempt to invoke virtual method ... on a null object reference" crash is by far our most common crash on Android. It's the most serious issue we have with Podverse on Android.

![image](https://user-images.githubusercontent.com/2262919/139760046-07e9ea9d-9664-4380-bd6c-c8a18eae483b.png)

**Comment by mattiaefesto** [comment] 2021-11-02 13:23
I can confirm it's happening also in V2

**Comment by dcvz** [comment] 2021-11-05 11:03
Thanks for the updates here, are any of you able to try our current pre release of the Android rewrite? 
We believe we've sorted out a whole class of crashes there, but would love some feedback.

**Comment by kreonjr** [comment] 2021-11-05 20:41
Hey @dcvz, we tried installing the beta on Podverse but we are getting the following Kotlin error on built time:

```
A problem occurred evaluating project ':react-native-track-player'.
> Plugin with id 'kotlin-android' not found.
```

I think there is something like an import missing in your node_module export. Not sure what it is because I've not dabbled with Kotlin too much.

cc @mitchdowney

**Comment by dcvz** [comment] 2021-11-05 21:09
@kreonjr dod you follow the instructions here: https://github.com/DoubleSymmetry/react-native-track-player/discussions/1264 ?

**Comment by mrigo** [comment] 2021-12-10 09:58
Hi, we can't upgrade to apiLevel 31 because of others dependencies of libraries not updated, so we are facing this issues in version 2.1.2...

**Comment by bradleyflood** [comment] 2022-01-15 10:52
This should be fixed in #1371 

Can y'all help us test this out and see?

@mrigo @kreonjr @mattiaefesto @nickmcmillan @mohity777

**Comment by jspizziri** [comment] 2022-04-13 13:35
@mrigo , all the energy is currently going into the v2.2.0 and beyond. Were you able to upgrade your project to use a newer version of the package?

**Comment by jspizziri** [comment] 2022-04-13 14:44
> Hi, we can't upgrade to apiLevel 31 because of others dependencies of libraries not updated, so we are facing this issues in version 2.1.2...

@mrigo the update to the apiVersion are the result of t[he upgrade in RN v0.68](https://reactnative.dev/blog/2022/03/30/version-068#highlights-of-068) we're going to try and stay in sync with RN.

Because all the energy is going into v2.2.0 this issue will be left open for now but will be closed once that version is formally released (as it appears that version will solve all the issues raised here).

**Comment by MaxJadav** [comment] 2022-04-26 09:53
Get crash in androind12 any quick solution?

I am using "react-native": "0.67.2"
   	minSdkVersion = 23
        compileSdkVersion = 31
        targetSdkVersion = 31

![Screenshot 2022-04-26 at 3 22 00 PM](https://user-images.githubusercontent.com/31030098/165273843-f81bdddf-b87d-4253-96ff-8a2ebe20b4f0.png)

**Comment by testfilee15** [comment] 2022-05-03 03:50
I've tried building version v2.2.0-rc3 for android but it crashes immediately without any runtime errors. I'm not sure if I'm the only one encountering this?

**Comment by jspizziri** [comment] 2022-05-03 05:10
@testfilee15  I've not seen that. Take a look at the example project. That builds and runs just fine and it's using main

**Comment by testfilee15** [comment] 2022-05-04 00:55
It looks like it was a version issue, I upgraded to the v2.2.0-rc3 and now it's all good. Thanks!

**Comment by brantleyenglish** [comment] 2022-06-08 15:22
I was testing `v2.2.0-rc3` on an Android 12 emulator, and it lost the app icon and used the generic Android app icon. 
I then switched back to `^2.1.3` and the icon was back to normal. I have no idea how this could be related, but it may be something to look for. The only tracked file changes were package.json, yarn.lock, and Podfile.lock.

**Comment by jspizziri** [comment] 2022-08-30 18:52
`v3.1` is now out. If you're having issues with Android 12 please upgrade to the latest version.

**Closed by jspizziri** 2022-08-30 18:52 UTC
Labels: Bug, Platform: Android, android-rewrite

**Comment by mschouhan123** [comment] 2022-11-22 09:01
> `v3.1` is now out. If you're having issues with Android 12 please upgrade to the latest version.

this work for me with that you also have to update your gradle also.
