### ISSUE TITLE
HLS work but its freeze the screen for few seconds

### ISSUE THREAD

**Issue by ninacoder-info** [doublesymmetry/react-native-track-player#1460] opened 2022-04-01 19:08 UTC
Hi, I have been using this library for couple years, everything great, but one small thing that I got HLS working on both iOS and Android.

On Android everything works just fine, but on iOS every time switching track (HLS) the screen will be freeze for 2 or 3 seconds then player starting to play normally. i can't touch scroll or do anything, even the animation running on screen get freeze too. This bug had been there for 2 or 3 years i dont remember. Any workaround?

Thanks so much

**Comment by dcvz** [comment] 2022-04-12 19:54
@ninacoder-info are you able to provide an example project we can use to test and see the issue?

**Comment by jspizziri** [comment] 2022-04-14 14:35
@ninacoder-info also, can you please let us know what version of the library you're on?

**Comment by jspizziri** [comment] 2022-04-26 10:52
We'll need more info to fix this. I'm going to close this issue but will reopen if we get a response.

**Closed by jspizziri** 2022-04-26 10:52 UTC
Labels: Bug, Platform: iOS, Needs Feedback

**Comment by ninacoder-info** [comment] 2022-05-06 09:00
Oh sorry, I'm on the latest version of track-player and also react-native, but I have been using track-player for couple years and that problem was there all the time.

Maybe its because my HLS was encrypted, may that cause freeze trouble?

Here is the HLS link if you guy like to test it our, just play it on iOS you will see (android work perfectly)

HLS LINK: https://musicengine.top/stream/hls/49/hd

**Comment by ninacoder-info** [comment] 2022-05-08 14:09
Hi, I'm using "react-native-track-player": "^2.1.3",

**Comment by jspizziri** [comment] 2022-05-08 17:37
@ninacoder-info that doesn't seem to be a valid HLS stream from what I can tell. I simply tried playing it with [HLSPlayer.org](https://www.hlsplayer.org/) with no success. I expected a `.m3u8` extension so I tried a few variants of the URL you provided:

- https://musicengine.top/stream/hls/49/hd
- https://musicengine.top/stream/hls/49/hd.m3u8
- https://musicengine.top/stream/hls/49/hd/index.m3u8

Are you sure the problem isn't your HLS stream itself?

**Comment by ninacoder-info** [comment] 2022-05-15 03:03
Hi, even if is my HLS link problem, the app should not be freeze right, it's just a stream link, it should return error or something if not able to play. But the stream link play well, just freeze the whole app for few seconds.

**Comment by jspizziri** [comment] 2022-05-16 15:54
Actually update, I just successfully played the URL you sent in the example app. I did have to hit the play button twice however, not sure why that happened.

**Comment by ninacoder-info** [comment] 2022-05-17 04:07
Hi, I will record a short email to prove it. But it's only happened on iOS, not android

Thank you

**Comment by jspizziri** [comment] 2022-05-17 09:50
It was working for me on iOS in the example project. Please try it there

**Comment by AlirezaHadjar** [comment] 2022-08-30 05:37
Facing the same issue here.

https://user-images.githubusercontent.com/57192409/187357889-2253b140-427f-46e0-b51c-e42c8748d2c5.mov

**Comment by jspizziri** [comment] 2022-08-30 09:45
What version are you using? Is this iOS or android? Did you specify the type property on the track? And if it's pre-version 3.0 did you specify build options?

**Comment by AlirezaHadjar** [comment] 2022-08-30 09:56
It happens on IOS. I'm also using version "3.1.0". and here are the track properties:
` {
			id: audio.id,
			url: audio.audio_file_details,
			artist: content.coach.name,
			artwork: content.main_image_details.url,
			pitchAlgorithm: PitchAlgorithm.Voice,
			title: content.name,
			description: content.description ? content.description : undefined,
			type: TrackType.HLS,
		}`

**Comment by jspizziri** [comment] 2022-08-30 10:14
Can you replicate the issue with the track included in the example project?

**Comment by AlirezaHadjar** [comment] 2023-10-26 12:16
Sorry for the delay in the response.
I can confirm that the issue is resolved in the v4.0
Nice job 🚀

**Comment by waheedakhtar694** [comment] 2023-11-08 16:11
I can confirm too, was facing the issue in the alpha version of v4 but after moving on `v4.0.1` is resolved.
