### ISSUE TITLE
Capabilities Bugs -> SkipToPrevious always showing and empty progressBar

### ISSUE THREAD

**Issue by RamProg** [doublesymmetry/react-native-track-player#1701] opened 2022-09-06 15:32 UTC
**Describe the Bug**

After updating from 2.1.2 to 3.1.0, I'm having two issues with the Android Media Control Capabilites.

1) The progress bar is empty. It's there, but not showing progress and you can't change the position from it.

2) When you expand the notification, you always get a SkipToPrevious button (similar to << ), even if I don't want it.

**Steps To Reproduce**

I haven't changed the capabilities while setting the update, so not sure why this is happening.

**Code To Reproduce**
```
TrackPlayer.updateOptions({
  stoppingAppPausesPlayback: true,
  alwaysPauseOnInterruption: false,
  forwardJumpInterval: 15,
  backwardJumpInterval: 15,
  jumpInterval: 15,
  capabilities: [
    Capability.Play,
    Capability.Pause,
    Capability.SeekTo,
    Capability.JumpForward,
    Capability.JumpBackward,
  ],
  compactCapabilities: [
    Capability.Play,
    Capability.Pause,
    Capability.JumpForward,
    Capability.JumpBackward,
  ],
});
```
<img src="https://user-images.githubusercontent.com/64564058/188675395-3af3be4f-c266-4a7d-b5e2-0963a419ea06.png" alt="screen" width="200"/>

**Environment Info:**

```
info Fetching system and libraries information...
System:
    OS: macOS 12.2.1
    CPU: (10) x64 Apple M1 Max
    Memory: 27.98 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.15.0/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
    Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

`react-native-track-player v3.1.0`
Same issue on device and simulator.

What OS are you running?
The issue happens only on Android.

**How I can Help**

I don't really understand yet what causes this.

**Comment by jspizziri** [comment] 2022-09-06 15:35
@RamProg I believe the issue with the progress bar is addressed by this PR https://github.com/doublesymmetry/react-native-track-player/pull/1668. Please install the nightly version if you need it right away.

The second issue sounds like a duplicate of https://github.com/doublesymmetry/react-native-track-player/issues/1698

I'm closing this issue on those grounds. If you think I'm missing something let me know and I can reopen.

**Closed by jspizziri** 2022-09-06 15:35 UTC
Labels: Bug

**Comment by RamProg** [comment] 2022-09-06 15:41
1) I read the discussion. It looks like you guys worked on the seek function, but I can't even see the dot on the bar. Was this addressed too or is it a different issue?

2) No, it's similar, but it's actually the opposite, that issue is about skipToNext now showing and mine is about skipToPrevious showing all the time (can't get rid of it).

So yeah, it would be great if you can reopen it. Thank you.

**Comment by jspizziri** [comment] 2022-09-06 15:45
@RamProg 

1. If you see [mpivchen's comment](https://github.com/doublesymmetry/react-native-track-player/pull/1668#issuecomment-1231761612), you'll see that after the fixes he put in place he couldn't reproduce it. So at some point in the work on KotlinAudio it got fixed. I tested and verified it. So it should be good, please try nightly.
2. Thanks for the info. Since they're so related I think I'd like to address them all on the same Issue.

I'm going to leave this issue closed and update the other to incorporate your issue.
