### ISSUE TITLE
Player does not play on IOS 12 (iPhone 6)

### ISSUE THREAD

**Issue by gustavo-amaro** [doublesymmetry/react-native-track-player#1440] opened 2022-03-21 18:20 UTC
**Describe the bug**
Similar the issue reported by [bahtiyarerden](https://github.com/bahtiyarerden) on issue [#1153](https://github.com/DoubleSymmetry/react-native-track-player/issues/1153) which has been closed. Player does work properly Android and newer IOS versions. But on IOS 12(iPhone 6) reproduce the issue. Player does not respond anything. In the xcode log file AudioHAL_Client gives a message `the stream index is out of range`.

```
Resetting player.
Starting/Resuming playback
2022-03-21 15:12:45.802829-0300 myrockfellermobile[60842:290766] [AudioHAL_Client] HALB_IOBufferManager.cpp:226:GetIOBuffer:  HALB_IOBufferManager::GetIOBuffer: the stream index is out of range
2022-03-21 15:12:45.802989-0300 myrockfellermobile[60842:290766] [AudioHAL_Client] HALB_IOBufferManager.cpp:226:GetIOBuffer:  HALB_IOBufferManager::GetIOBuffer: the stream index is out of range
2022-03-21 15:12:45.820945-0300 myrockfellermobile[60842:290766] [aqme] 254: AQDefaultDevice (1): output stream 0: null buffer
2022-03-21 15:12:45.821184-0300 myrockfellermobile[60842:290766] [aqme] 1640: EXCEPTION thrown (-50): -
```

**To Reproduce**
1- Run player iPhone 6(ios 12) on simulator

**Environment (please complete the following information):**
Run `react-native info` in your project and share the content.

```
System:
    OS: macOS 11.3
    CPU: (4) x64 Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz
    Memory: 166.45 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.2.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.1.4 - /usr/local/bin/npm
    Watchman: 2021.12.06.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 31.0.0
      System Images: android-29 | Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7583922
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**What react-native-track-player version are you using?**
`2.0.1`

**Code**
Please, share the code that is causing the issue

```
 const track = {
    id: audioUrl,
    url: audioUrl.search('%40') > 0 ? audioUrl : decodeURI(audioUrl),
    title: 'Audio Test',
    artist: 'Test',
  };

  TrackPlayer.setupPlayer()
    .then(() => {
      TrackPlayer.add([track])
        .then(() => {
          TrackPlayer.play();
          setAudioPlaying(track.id);
        })
        .catch((err) => {
          console.log('error: ', err);
        });
    })
    .catch((err) => {
      console.log('error: ', err);
    });
```

**Comment by jspizziri** [comment] 2022-04-13 16:03
@gustavo-amaro does this issue currently happen in v2.2.0-rc3?

**Comment by jspizziri** [comment] 2022-04-19 18:13
I've confirmed this behavior, however after looking more deeply into it looks like:

1. This issue should actually be filed with [SwiftAudioEx](https://github.com/doublesymmetry/SwiftAudioEx)
2. This is really a feature request and not a bug.

With both of those things in mind, I'm going to close this issue. If you disagree please let me know.

**Comment by jspizziri** [comment] 2022-04-19 18:14
Sorry, closed by mistake.

**Comment by jspizziri** [comment] 2022-04-19 18:46
@gustavo-amaro ,

I just tested this with the example project on a simulator (iPhone 6, iOS 12.4). Everything worked exactly as I would expect. Please upgrade to v2.2.0-rc3 and retest. If you're still having issues please create a reproducible repo that can help us debug the issue and I will reopen.

**Closed by jspizziri** 2022-04-19 18:46 UTC
Labels: Platform: iOS, Needs Feedback
