### ISSUE TITLE
Track index given to Event.PlaybackTrackChanged from Android is always undefined

### ISSUE THREAD

**Issue by taylorakin17** [doublesymmetry/react-native-track-player#1603] opened 2022-07-19 20:01 UTC
**Describe the Bug**
When listening for the `Event.PlaybackTrackChanged` event, the `track` index coming from Android is inconsistent (and seemingly incorrect) when compared to the `track` index coming from iOS. When a track completes and moves on to the next one in the queue on iOS, it provides some integer for the track index (such as 0, 1, 2, etc.). However, when a track completes and moves on to the next one in the queue on Android, it provides a value of `undefined` in place of the correct index for the track that just finished playing.

**Steps To Reproduce**
1. Add audio guides to a queue using `TrackPlayer.add()`
2. Add the event listener for `Event.PlaybackTrackChanged`
3. `console.log()` the `track` parameter and observe the value logged on iOS (correct) vs Android (incorrect)

**Code To Reproduce**
```
TrackPlayer.addEventListener(
    Event.PlaybackTrackChanged,
    async ({ track, nextTrack, position }) => {
      console.log('value of track:', track);
      // track == 0 on iOS
      // track == undefined on Android
   }
)
```

**Environment Info:**
```
System:
    OS: macOS 12.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 23.38 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.5.0 - /usr/local/bin/node
    Yarn: 3.2.1 - /usr/local/bin/yarn
    npm: 8.12.1 - /usr/local/bin/npm
    Watchman: 2022.07.04.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /Users/taylorakin/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.2 - /usr/bin/javac
    Python: 3.8.8 - /Users/taylorakin/opt/anaconda3/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
```
"react-native-track-player": "git+https://github.com/doublesymmetry/react-native-track-player.git#44b56147c53e833de7b8fe9b6b26b8413d9ae7d9"
```
This is running on an Android 11 (API 30) emulator and an iOS 15.5 iPhone 11 simulator

**Comment by jspizziri** [comment] 2022-07-19 20:46
@taylorakin17 what version of the library are you using?

**Comment by taylorakin17** [comment] 2022-07-19 20:48
> @taylorakin17 what version of the library are you using?

We are targeting a specific commit (`44b56147c53e833de7b8fe9b6b26b8413d9ae7d9`) because we needed the a fix that wasn't yet released @jspizziri.

**Comment by jspizziri** [comment] 2022-07-19 20:53
@taylorakin17 ahh, looking at this this is a known issue with a PR in place to fix it (it just hasn't been merged yet).

https://github.com/doublesymmetry/react-native-track-player/pull/1501

**Comment by taylorakin17** [comment] 2022-07-19 20:56
Ah, I see. My apologies for the duplicate issue. I can close it, or leave it for reference. Which do you prefer? (And do you happen to know if the fix for this will be merged soon?)

**Comment by jspizziri** [comment] 2022-07-19 20:59
No worries, I'm going to close it as a duplicate of https://github.com/doublesymmetry/react-native-track-player/issues/1389

We haven't merged the existing PR because there were some other issues we wanted to address on it too. But I just started a conversation with the rest of the team to see if we should just merge it now and address the other issues later.

I should have some more info tomorrow.

**Closed by jspizziri** 2022-07-19 20:59 UTC
Labels: Bug, Platform: Android

**Comment by taylorakin17** [comment] 2022-07-19 21:00
Great, thanks! I appreciate it. Looking forward to your response, and do let me know if you need anything from me!

**Comment by taylorakin17** [comment] 2022-07-20 14:59
@jspizziri Great, thank you!

**Comment by jspizziri** [comment] 2022-07-20 15:50
@taylorakin17 it's been merged.

**Comment by taylorakin17** [comment] 2022-07-20 16:10
@jspizziri Awesome, thank you!
