### ISSUE TITLE
Doesn't play all the songs when large number song is added

### ISSUE THREAD

**Issue by simdanonline** [doublesymmetry/react-native-track-player#1735] opened 2022-09-16 12:50 UTC
**Describe the Bug**
The entire list of songs isn't played before it restarts all over again.
For example, if I have added 100 tracks, I expect the 100 tracks to have been played before it starts all over.
But most times, it plays a couple of the tracks then restart from the beginning.

**Steps To Reproduce**
How can someone else reproduce this bug?

`const formattedTracks = [
        {
          id: 1,
          url: https://the-song-url.mp3,
          title: 'song title,
          artist: 'artist',
          type: 'track fileType',
        },
       ....,
       {
          id: 350,
          url: https://the-song-url.mp3,
          title: 'song title,
          artist: 'artist',
          type: 'track fileType',
        }
]
await TrackPlayer.add(formattedTracks);

`
**Environment Info:**
Paste the results of `Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.10.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.4 => 0.67.4 `
Paste the exact `"react-native-track-player": "^2.1.2"` version you are using
Real device? Or simulator? : Both
What OS are you running? Android

**Comment by jspizziri** [comment] 2022-09-16 13:04
Please create a repro in the example project based off of a fork of this repo.

**Comment by jspizziri** [comment] 2022-09-20 14:42
@simdanonline , in the next few days I'm going to close this due to inactivity if I don't here back.

**Comment by jspizziri** [comment] 2022-09-21 11:28
I also just noticed that you're using v2.1.2. Please upgrade to v3 as the android side was entirely rewritten. I'm closing this as completed until someone can provide a reproduction based off of `main`

**Closed by jspizziri** 2022-09-21 11:28 UTC
Labels: Bug, Platform: Android, Needs Feedback, Unconfirmed
