### ISSUE TITLE
Playing URL crashes...

### ISSUE THREAD

**Issue by export-mike** [DoubleSymmetry/react-native-track-player#1130] opened 2021-03-09 23:18 UTC
Following URL crashes iOS:

http://www.mediafire.com/file/clcf947zz6nazg1/Expert+Insights-+Using+TMS+and+Ketamine+to+Treat+Depression.mp3

The following URL works:

http://feedproxy.google.com/~r/BeingWellBlackDogInstitutePodcasts/~5/N427w4aXbvA/Being_Well_Shaii%2527s_Story_2.mp3

I'm unable to debug this as I'm getting  `<invalid swift context>`

![image (4)](https://user-images.githubusercontent.com/2983327/110551600-ebb5e080-8189-11eb-8da3-d2e888aa173e.png)

**Comment by export-mike** [comment] 2021-03-24 02:03
Updated same mp3 just hosted differently. any ideas?

Working Response headers:
michaeljames@Michaels-MacBook-Pro mp3 % curl -I http://localhost:5000/What-makes-a-good-boss-with-Amy-Coopes-Eloise-Sobels-and-Rhea-Liang.mp3
HTTP/1.1 200 OK
Content-Length: 53200515
Content-Disposition: inline; filename="What-makes-a-good-boss-with-Amy-Coopes-Eloise-Sobels-and-Rhea-Liang.mp3"
Accept-Ranges: bytes
ETag: "c9ebd9c3a3e3d3f6a06789dae8da70d4bdc4104a"
Content-Type: audio/mpeg
Date: Wed, 24 Mar 2021 01:33:12 GMT
Connection: keep-alive


Not Working Response headers:
michaeljames@Michaels-MacBook-Pro mp3 % curl -I "https://onthewards.org/wp-content/uploads/2021/03/What-makes-a-good-boss-with-Amy-Coopes-Eloise-Sobels-and-Rhea-Liang.mp3?raw=1"
HTTP/2 200 
date: Wed, 24 Mar 2021 01:33:31 GMT
content-type: audio/mpeg
content-length: 53200515
set-cookie: __cfduid=d3e4fb8ddead9304f4e20b70eeda810941616549611; expires=Fri, 23-Apr-21 01:33:31 GMT; path=/; domain=.onthewards.org; HttpOnly; SameSite=Lax; Secure
vary: X-Forwarded-Proto,Accept-Encoding,User-Agent
last-modified: Tue, 09 Mar 2021 05:57:16 GMT
accept-ranges: bytes
cache-control: max-age=31536000, public
expires: Thu, 24 Mar 2022 01:33:31 GMT
x-httpd: 1
referrer-policy: no-referrer-when-downgrade
pragma: public
x-powered-by: W3 Total Cache/2.1.1
host-header: 8441280b0c35cbc1147f8ba998a563a7
x-proxy-cache-info: DT:1
cf-cache-status: DYNAMIC
cf-request-id: 0903769f0100003772a18f7000000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"group":"cf-nel","max_age":604800,"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=fXAkOJA55q0OVuYi%2B0qXpRDr84999L2Gq5xJXUpncwIC1TuqhJzTW13J3%2F31CtYHpXlq3VkZ3%2FgajqXZLjLhpCLiVSvgPs0GkDso9G%2BbeA%3D%3D"}]}
nel: {"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 634c26de6cbd3772-MEL
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400

**Comment by gaodeng** [comment] 2021-03-24 02:32
Try to install the latest version. The crash was caused by an illegal character in the url, which has been fixed in the latest version https://github.com/react-native-kit/react-native-track-player/pull/950

**Comment by export-mike** [comment] 2021-03-24 02:58
1.2.7? I'm running that version @gaodeng

**Comment by curiousdustin** [comment] 2021-03-24 14:10
Testing on an iPhone 7 with iOS 14. In debug build mode.

Both of the URLs from the original post play for me in the example app using version `1.2.7`.

1) http://www.mediafire.com/file/clcf947zz6nazg1/Expert+Insights-+Using+TMS+and+Ketamine+to+Treat+Depression.mp3
2) http://feedproxy.google.com/~r/BeingWellBlackDogInstitutePodcasts/~5/N427w4aXbvA/Being_Well_Shaii%2527s_Story_2.mp3

However, the public example from your second post DOES fail for me with an `unknown error`.

3) https://onthewards.org/wp-content/uploads/2021/03/What-makes-a-good-boss-with-Amy-Coopes-Eloise-Sobels-and-Rhea-Liang.mp3?raw=1

If I log the error from within the native code the full error is:

```
Error 
Domain=NSURLErrorDomain
Code=-1 "unknown error"
UserInfo={
    NSUnderlyingError=0x28357b180 {
        Error
        Domain=CoreMediaErrorDomain
        Code=-12939
        "content range mismatch - should be start 0 length 53200515 is start 0 length 1"
        UserInfo={
            NSDescription=content range mismatch - should be start 0 length 53200515 is start 0 length 1,
            NSURL=https://onthewards.org/wp-content/uploads/2021/03/What-makes-a-good-boss-with-Amy-Coopes-Eloise-Sobels-and-Rhea-Liang.mp3?raw=1
        }
    },
    NSErrorFailingURLStringKey=https://onthewards.org/wp-content/uploads/2021/03/What-makes-a-good-boss-with-Amy-Coopes-Eloise-Sobels-and-Rhea-Liang.mp3?raw=1, NSErrorFailingURLKey=https://onthewards.org/wp-content/uploads/2021/03/What-makes-a-good-boss-with-Amy-Coopes-Eloise-Sobels-and-Rhea-Liang.mp3?raw=1, NSURL=https://onthewards.org/wp-content/uploads/2021/03/What-makes-a-good-boss-with-Amy-Coopes-Eloise-Sobels-and-Rhea-Liang.mp3?raw=1,
    NSLocalizedDescription=unknown error
}
```

**Comment by curiousdustin** [comment] 2021-03-24 14:12
I don't have time at the moment to dig deeper, however, this is the only lead a quick googling came up with: https://stackoverflow.com/questions/47454359/ios-not-playing-some-videos-coremediaerrordomain-code-12939?noredirect=1#comment81864268_47454359

The accepted answer blames the server setup.

**Comment by export-mike** [comment] 2021-03-24 23:12
@curiousdustin thanks for your help :) 

http://www.mediafire.com/file/clcf947zz6nazg1/Expert+Insights-+Using+TMS+and+Ketamine+to+Treat+Depression.mp3 seems to be returning a HTML web page for me. very random. due to how its hosted not this package.

**Closed** 2021-08-10 16:57 UTC
Labels: Bug, Needs Confirmation
