### ISSUE TITLE
iOS not building

### ISSUE THREAD

**Issue by colindaly** [DoubleSymmetry/react-native-track-player#1234] opened 2021-08-19 06:58 UTC
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal x86_64 /Users/mbp18/Documents/WIP/Unknown\ FM/www/dev/react-native-track-player/example/ios/Pods/YogaKit/YogaKit/Source/YGLayoutExtensions.swift
	PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/mbp18/Library/Developer/Xcode/DerivedData/example-cunuzjrqgjhdjbfnymvuvggspgbf/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBReactNativeSpec.build/Script-F4B27350C08B579FDF25545126872666.sh
(2 failures)

**Environment (please complete the following information):**
Run `react-native info` in your project and share the content.
System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 273.25 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 7.6.3 - /usr/local/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 29, 30
      Build Tools: 29.0.2, 30.0.2, 30.0.3
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7583922
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.1 => 0.64.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

What `react-native-track-player` version are you using?
2.0.2
Are you testing on a real device or in the simulator? Which OS version are you running?
iOS Simulator - iPhone 12 - iOS 14.4

**Code**
Please, share the code that is causing the issue

**Comment by dcvz** [comment] 2021-08-19 07:18
@colindaly is this when running the example or trying to use the library in your project?

Others have been able to use this package successfully in their iOS project. Have you tried clearing the cache?
`react-native start -- --reset-cache`

**Comment by colindaly** [comment] 2021-08-19 08:32
Hi David. Thanks for your prompt reply. I’ve cloned the repo, cd example and run ‘npm react-native run-ios’. Android sim didn’t work either.

**Comment by dcvz** [comment] 2021-08-19 08:51
so does it fail to build? or does it fail to run?

**Comment by colindaly** [comment] 2021-08-20 01:04
@dcvz I've nuked the folder and cloned the repo again. Actions are as follows....

cd react-native-track-player
cd example
npm install

`npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: example@0.0.1
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.11.0" from @react-native-community/slider@4.0.0-rc.3
npm ERR! node_modules/@react-native-community/slider
npm ERR!   @react-native-community/slider@"4.0.0-rc.3" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/mbp18/.npm/eresolve-report.txt for a full report.`

**Comment by dcvz** [comment] 2021-08-20 07:18
@colindaly it seems to me the problem is happening because there's no dependency lock file for npm.

Try using yarn install instead, because there's already a lock file for dependencies and there should be no conflicts.

**Comment by colindaly** [comment] 2021-08-20 07:44
Yes, you’ll see halfway down my last comment I used yarn, but it still didn’t build as you’ll see in the log towards the bottom. Android did this time which is good.

**Comment by dcvz** [comment] 2021-08-20 08:05
@colindaly sorry missed that part of the log.. weird. One of the ReactNative scripts seems to be failing.

Can you try putting this project in a path that does not contain a space?

**Comment by espenjanson** [comment] 2021-08-20 11:34
Does not build for me either, react-native 0.65, I get an warning about...

`[!] Unable to read the license file `LICENSE` for the spec `SwiftAudioEx (0.13.2)`
`

And then I get the following errors as I build:

`The following build commands failed:
	CompileSwift normal x86_64 /Users/espenjanson/Sites/napper-app/node_modules/react-native-track-player/ios/RNTrackPlayer/Models/Capabilities.swift
	CompileSwift normal x86_64 /Users/espenjanson/Sites/napper-app/node_modules/react-native-track-player/ios/RNTrackPlayer/Vendor/SwiftAudio/Classes/Utils/DispatchQueueType.swift
	CompileSwift normal x86_64 /Users/espenjanson/Sites/napper-app/node_modules/react-native-track-player/ios/RNTrackPlayer/Models/MediaURL.swift
	CompileSwift normal x86_64 /Users/espenjanson/Sites/napper-app/node_modules/react-native-track-player/ios/RNTrackPlayer/Utils/Metadata.swift
	CompileSwift normal x86_64 /Users/espenjanson/Sites/napper-app/node_modules/react-native-track-player/ios/RNTrackPlayer/Models/PitchAlgorithms.swift
	CompileSwift normal x86_64 /Users/espenjanson/Sites/napper-app/node_modules/react-native-track-player/ios/RNTrackPlayer/Vendor/SwiftAudio/Classes/RepeatMode.swift
	CompileSwift normal x86_64 /Users/espenjanson/Sites/napper-app/node_modules/react-native-track-player/ios/RNTrackPlayer/RNTrackPlayer.swift
	CompileSwift normal x86_64 /Users/espenjanson/Sites/napper-app/node_modules/react-native-track-player/ios/RNTrackPlayer/Models/SessionCategories.swift
	CompileSwift normal x86_64 /Users/espenjanson/Sites/napper-app/node_modules/react-native-track-player/ios/RNTrackPlayer/Models/Track.swift
	PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/espenjanson/Library/Developer/Xcode/DerivedData/napper-eirljtrfgvujadbjavexhwhitldn/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBReactNativeSpec.build/Script-766FED219AE6322712F6EC918B59DEFB.sh
`

I've tried every trick in the book.

**Comment by dcvz** [comment] 2021-08-20 11:37
@espenjanson is this with the example app? Or your own project?

**Comment by espenjanson** [comment] 2021-08-20 11:38
@dcvz my own app, not example project. But the error seems very similar to the one @colindaly has?

**Comment by dcvz** [comment] 2021-08-20 11:39
@espenjanson yeah it looks similar.. trying to understand what's happening for you all. I haven't heard of this issue before.

Can you try also running the example?

**Comment by dcvz** [comment] 2021-08-20 11:39
Also what xcode version are you on @espenjanson ?

**Comment by espenjanson** [comment] 2021-08-20 11:40
@dcvz can't run example right now due to time constraint but could try later today. I am on 12.4, but currently trying to upgrade to 12.5.1. Takes forever as you know.

**Comment by dcvz** [comment] 2021-08-20 11:42
That's interesting information. Would be good if you could check the example app and also curious to know if it works on 12.5.1.

**Comment by espenjanson** [comment] 2021-08-20 11:44
@dcvz absolutely, will check later. Thanks for quick reply!

**Comment by espenjanson** [comment] 2021-08-20 18:04
@dcvz @colindaly Happy times! I don't think it's this lib, I rather think there's a bug in react-native:

See

https://stackoverflow.com/questions/68295582/i-got-an-error-while-trying-to-do-pod-install-fbreactnativespec-has-added-1

I added react-native-codegen etc. and it built.

**Comment by dcvz** [comment] 2021-08-20 18:06
Glad to hear it @espenjanson ! Does this fix things for you @colindaly ?

**Comment by dcvz** [comment] 2021-08-20 19:54
For further information: this is actually mentioned by the RN team in their release post for 0.65.0.

https://reactnative.dev/blog/2021/08/17/version-065#notable-dependency-version-updates-and-gotchas

**Comment by colindaly** [comment] 2021-08-21 00:27
I'm afraid not. Added react-native-codegen as @espenjanson mentioned (thank you), but still getting an error.
> The following build commands failed:
	PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/mbp18/Library/Developer/Xcode/DerivedData/example-cunuzjrqgjhdjbfnymvuvggspgbf/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBReactNativeSpec.build/Script-0F6B92E5EBFC7D4F4770D3E1B8028AB2.sh

**Comment by colindaly** [comment] 2021-08-21 00:53
OK. Got it working!!!
After the above fail, I ran
- yarn add react-native-track-player
- react-native run-ios

And it built!

I'm still getting some erros in iOS Simulator, but should be an easy fix
>Could not find image file:///Users/mbp18/Library/Developer/CoreSimulator/Devices/9A5DC182-4B1A-417A-B233-AEADBDAD6155/data/Containers/Bundle/Application/BF4AE662-E5C7-4B79-8A41-330DF025543F/example.app/undefined.png

Thank you @dcvz and @espenjanson for your help. Its greatly appreciated.

**Comment by dcvz** [comment] 2021-08-21 06:04
Glad to hear it @colindaly ! I will go ahead and close this issue then.

**Closed by dcvz** 2021-08-21 06:04 UTC
Labels: Bug, Needs Confirmation
