### ISSUE TITLE
[Android][RC-04] Crash: Unable to start service com.doublesymmetry.trackplayer.service.MusicService@78647c9 with null #1986

### ISSUE THREAD

**Issue by ZeroPie** [doublesymmetry/react-native-track-player#1999] opened 2023-04-25 01:11 UTC
**Describe the Bug**`

Firebase Analytics is reporting the following crash
```
Fatal Exception: java.lang.RuntimeException: Unable to start service com.doublesymmetry.trackplayer.service.MusicService@78647c9 with null: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service com.dierotenbullen.app/com.doublesymmetry.trackplayer.service.MusicService
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5192)
       at android.app.ActivityThread.access$2200(ActivityThread.java:315)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2324)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8751)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
       
```
      
       
```
       Caused by android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service com.rnapp.app/com.doublesymmetry.trackplayer.service.MusicService
       at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
       at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
       at android.os.Parcel.readParcelable(Parcel.java:3346)
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2433)
       at android.os.Parcel.createException(Parcel.java:2422)
       at android.os.Parcel.readException(Parcel.java:2405)
       at android.os.Parcel.readException(Parcel.java:2347)
       at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:8095)
       at android.app.Service.startForeground(Service.java:733)
       at com.doublesymmetry.trackplayer.service.MusicService.startAndStopEmptyNotificationToAvoidANR(MusicService.kt:115)
       at com.doublesymmetry.trackplayer.service.MusicService.onStartCommand(MusicService.kt:92)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5174)
       at android.app.ActivityThread.access$2200(ActivityThread.java:315)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2324)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8751)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```
**Steps To Reproduce**
`Alas cannot reproduce, but firebase analytics reports the crashes.`

**Code To Reproduce**
use "react-native-track-player": "^4.0.0-rc03"

**Replicable on Example App?**
Alas not replicable

**Environment Info:**
```System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 95.86 MB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.volta/tools/image/node/16.13.1/bin/node
    Yarn: 1.22.17 - ~/.volta/tools/image/yarn/1.22.17/bin/yarn
    npm: 8.19.2 - ~/.volta/tools/image/node/16.13.1/bin/npm
    Watchman: 2023.03.13.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 29, 30, 31, 33
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-31 | ARM 64 v8a, android-31 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.1 => 0.66.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Paste the exact `react-native-track-player` version you are using**
`"react-native-track-player": "^4.0.0-rc04"`


**How I can Help**
What can you do to help resolve this?
Have you investigated the underlying JS or Swift/Android code causing this bug?
Can you create a Pull Request with a fix?

**Comment by jspizziri** [comment] 2023-04-25 12:46
This... seems to be a duplicate of https://github.com/doublesymmetry/react-native-track-player/issues/1986 is there a reason you did that?

**Closed by jspizziri** 2023-04-25 12:46 UTC
Labels: Bug

**Comment by ZeroPie** [comment] 2023-04-25 14:12
> This... seems to be a duplicate of #1986 is there a reason you did that?

Sorry, i thought i mistakenly thought mine was a different error!
Thanks for closing and asking.
